### ISSUE TITLE
wine qq登入后崩溃的修复方式一

### ISSUE THREAD

**Issue by SunRain** [hillwoodroc/winetricks-zh#10]

**Comment by SunRain** [comment]
这个问题是我在ubuntu14.10 64位上碰到的,使用的wine是ubuntu上ppa里面的最新wine版本,表现就是qq正常登入后立即崩溃.
解决方式:在~/.local/share/wineprefixes/qq/drive_c/users/$UserName/Application Data/Tencent/QQ/Misc/下创建com.tencent.wireless/SDK 目录,并且chmod 000 SDK.发生此问题的原因,据说是由于qq会自动下载安卓助手相关的内容.

**Comment by hillwoodroc** [comment]
Fixed, thank you!

**Comment by admirestator** [comment]
这个问题在最新的QQ7.7上也出现了。该解决方法有效。多谢！

**Comment by secretwiki** [comment]
使用清风的wineqq遇到了一次，操作了没有效果，直接删除整个Tencent文件夹之后恢复了，感谢。
