### ISSUE TITLE
新版微信部分功能异常

### ISSUE THREAD

**Issue by jamewhite** [hillwoodroc/winetricks-zh#102]
微信大约从版本2.4开始右上角有一个”…“按钮，点开会从右侧出现好友或群聊的信息，但是在Wine中点击这个按钮只会在右侧闪一下，无法打开侧边菜单。望高手解决

下面是单击该按钮后终端输出的信息（总共单击六次，每次出现两行输出）：
fixme:win:RegisterTouchWindow (0x100b4 00000000): stub
fixme:win:IsTouchWindow (0x100b4 (nil)): stub
fixme:win:RegisterTouchWindow (0x200b4 00000000): stub
fixme:win:IsTouchWindow (0x200b4 (nil)): stub
fixme:win:RegisterTouchWindow (0x600b4 00000000): stub
fixme:win:IsTouchWindow (0x600b4 (nil)): stub
fixme:win:RegisterTouchWindow (0x500b6 00000000): stub
fixme:win:IsTouchWindow (0x500b6 (nil)): stub
fixme:win:RegisterTouchWindow (0x700b6 00000000): stub
fixme:win:IsTouchWindow (0x700b6 (nil)): stub
fixme:win:RegisterTouchWindow (0x900b6 00000000): stub
fixme:win:IsTouchWindow (0x900b6 (nil)): stub

**Comment by tonghuix** [comment]
可能是API变化导致的吧

**Comment by hillwoodroc** [comment]
你说的是这个吧，我这里美问题哦。我的 wine 版本是2.10。
![2017-06-27 22-30-05](https://user-images.githubusercontent.com/1880237/27592864-30476074-5b88-11e7-91cc-8076f56929f8.png)

**Comment by jamewhite** [comment]
我原本使用wine稳定版2.0.1，将其卸载换成了wine-devel 2.11，并用这里的wechat.verb安装微信，问题依旧。

我的系统是Ubuntu 16.04 LTS，Unity桌面。

**Comment by hillwoodroc** [comment]
我更新了下，把容器默认的系统版本设置成了 windows xp ，楼主试试看问题是否还在。

**Comment by jamewhite** [comment]
抱歉有事没有及时回复。

我刚刚测试了wine-stable的2.0.2和wine-devel的2.13，问题仍然存在，没有变化。

容器一直都设置为Windows XP

**Comment by hillwoodroc** [comment]
重现不了，不知道是不是桌面环境的问题。

**Comment by hillwoodroc** [comment]
今天遇到这个 bug 了，不过关掉窗口再重新打开又正常了。

**Comment by jamewhite** [comment]
您记得在什么情况下出现的吗？我这里在Ubuntu上从没正常过，我抽空在其他发行版上试一下。

**Comment by Durant35** [comment]
## 可能直接使用楼主的`winetricks-zh wechat`能够正常安装并使用吧，不过烦人的是微信官网的checksum又变了。。。
![image](https://user-images.githubusercontent.com/6770853/29274681-3590f954-813b-11e7-9b78-d630c659ccf5.png)
+ 以上，我采用直接通过wine安装，不过，需要先将容器一直设置为Windows 7及以上（安装最低版本要求），安装完成后改回Windows XP才能正常启动
+ 问题：编辑框无法显示光标；文件、表情、图片无法上传
    + 使用qq的`riched20.dll`：右上角状态栏会异常，无法点击

**Comment by hillwoodroc** [comment]
checksum 已经更新。

**Comment by jamewhite** [comment]
很抱歉有事未能及时回复。刚刚更新到微信2.5后发现侧边菜单可以正常显示了，非常感谢大家！

**Comment by firstuanl** [comment]
你好，微信不显示图片及2维码是少了哪个dll，

**Comment by jam178945** [comment]
不太清楚，可能是riched20.dll的问题，需要安装原版的riched20.dll，如果仍有问题将其设置为native。我使用微信版本2.5没有问题，最新版没试。
