### ISSUE TITLE
安装好后运行winetricks-zh出错

### ISSUE THREAD

**Issue by StandNorthStar** [hillwoodroc/winetricks-zh#106]
我安装完成后遇到这个错误，请问下这个怎么设置？
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

**Comment by IsoaSFlus** [comment]
这个不是错误，只是告诉你，你的prefix是64位的，有些verb是32位only的，但在这里没有影响，无视即可。

**Comment by StandNorthStar** [comment]
抱歉呀，我不是太会用这个．请问下这个应用怎么打开呢？

**Comment by IsoaSFlus** [comment]
读readme，上面说的很清楚了，同时也可以参考winetricks的资料。

**Comment by StandNorthStar** [comment]
你好，你看我执行的对吗？下面是我执行的命令
winetricks --isolate  youku.verb
－－－－－－－－－－－－－－－－－－－
root@hly-x450:/opt/winetricks-zh# WINE=/opt/cxoffice/bin/wine WINESERVER=/opt/cxoffice/bin/wineserver CX_BOTTLE=windows7 /opt/winetricks-zh/winetricks-zh ./verb/youku.verb 
Using winetricks 20170614-next - sha256sum: 6c24c0c9829176c65f29977bb11f14836ba7078893cfef57ffb705d1f6a2e7e2 with Product Name: CrossOver Linux
Public Version: 15.0.3
Product Version: 15.0.3.29638
Build Tag: 2834e0b98de534f50f31c62ed10750c382b78cbb
Build Timestamp: 20160624T125036Z and WINEARCH=win32
------------------------------------------------------
You are running winetricks-20170614-next, latest upstream is winetricks-20170823!
------------------------------------------------------
------------------------------------------------------
You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
------------------------------------------------------
bug: a verb named youku already exists.
------------------------------------------------------

**Comment by hillwoodroc** [comment]
那个 verb 文件是给上游 winetricks ，用的。Winetricks-zh 自带 youku, 直接 winetricks-zh
youku 就可以了。

2017年8月31日 17:05，"StandNorthStar" <notifications@github.com>写道：

**Comment by StandNorthStar** [comment]
（优酷下载地址过期404）问下我修改了下优酷的下载路径和文件名，这样再运行第二步还会出现原先那个下载404错误．
［旧包］9e059a|ERR |       0B/s|/root/.cache/winetricks/youku/youkuclient_setup_ywebtop1_6.7.7.12257.exe

**Comment by hillwoodroc** [comment]
地址我以及更新了，你再试试看。

**Comment by StandNorthStar** [comment]
谢谢，我试试
