### ISSUE TITLE
sha1sum mismatch!  Rename /home/%%%/.cache/winetricks/qq/QQ8.9.4.exe and try again.

### ISSUE THREAD

**Issue by SMZCC** [hillwoodroc/winetricks-zh#107]
sha1sum不知道是啥，希望大神们帮忙解释下如何进行修改才可以安装
谢谢

**Comment by yanquanyu** [comment]
应该就是校验下载的程序是否完整的，感觉应该脚本里面存在这个应用的sha1sum，根据你下载的程序进行比对，如果下载的程序中途终端导致不完整，那么两边的值不一致。多试几次应该可以。

**Comment by hillwoodroc** [comment]
你网络不好，或者被劫持了，下载的安装文件不对。

**Comment by SMZCC** [comment]
也就是说我要不停地尝试下载，直至某次成功是吗？ :sob:
