### ISSUE TITLE
qq没在任务栏显示，最小化之后找不到

### ISSUE THREAD

**Issue by yanquanyu** [hillwoodroc/winetricks-zh#109]
如题，请问这个需要怎么设置一下吗？ 系统是ubuntu16.04 内核4.9.26

**Comment by hillwoodroc** [comment]
这个可能是 unity 的问题。和传统通知托盘不兼容？

**Comment by yanquanyu** [comment]
我之前用网上的crossover破解之后安装了一个qq，这个qq是可以放到托盘上面的，但是现在装的这个不行，两者不一样么？

**Comment by yanquanyu** [comment]
@hillwoodroc  找到一个解决办法，安装`indicator-systemtray-unity`，安装如下：
```
> sudo apt-add-repository ppa:fixnix/indicator-systemtray-unity
> sudo apt-get update
> sudo apt-get install indicator-systemtray-unity
```
重启或者logout就可以了
