### ISSUE TITLE
请问能提供对itools下 ios录屏软件的 支持么

### ISSUE THREAD

**Issue by sherylynn** [hillwoodroc/winetricks-zh#11]
pc下的itools的[苹果录屏大师](http://pro.itools.cn/airplayer) 集成了 airplay和vnc的功能,挺好用的,
只是不知道软件需要什么运行库....只知道原生的windows镜像的系统就能直接运行

**Comment by hillwoodroc** [comment]
的确是不支持，到 wine 的 bugzilla 上报个 bug 吧。不过短期内修复的可能性不大。
