### ISSUE TITLE
安装微信运行的时候提示缺少qbcore.dll

### ISSUE THREAD

**Issue by chenyongkang93** [hillwoodroc/winetricks-zh#114]

**Comment by hillwoodroc** [comment]
那么运行是否正常？

**Comment by lyhlgf** [comment]
遇到同样的问题，并不能正常运行。
我是mac下，命令行的wine可以运行微信，但是加载不出来二维码，用winebottole安装的话就运行不了了，会报这个错误，具体错误信息貌似是微信的browser模块报出来的.
用的wine的版本是3.0.1-stable
winebottle的安装环境是win7
用的微信版本是目前官网最新的win-2.6.3
不是很了解wine，不过我估计是这个dll会在安装的时候去下载，所以导致了这个问题

**Comment by hillwoodroc** [comment]
不能重现，请升级 wine 再试。
