### ISSUE TITLE
sha256sum mismatch!

### ISSUE THREAD

**Issue by papabattery** [hillwoodroc/winetricks-zh#117]
我配置完winetricks-zh后按照步骤安装 提示：sha256sum mismatch! Rename /home/****/.cache/winetricks/wechat/WeChatSetup.exe and try again. 这个SHA256校验不匹配还是第一次遇到，会不会在更新的时候改了什么。我的系统格式Ubuntu16.04LTS，wine版本是2.4stable

**Comment by hillwoodroc** [comment]
哦哦，腾讯又更新版本了，我改一下。

2017年12月15日 08:39，"EarlyBird" <notifications@github.com>写道：

**Comment by papabattery** [comment]
还好 ，我刚才测试了几个   有道云和微信会出现sha256sum mismatch的问题，TIM能安装，但是出现卡顿和莫名消失的问题（就是在前台点了下突然就消失了，但是在启动栏的图标还在，讲所有的前台应用关闭后可以找到TIM） 优酷可以安装，但是装完不能点击直接死掉，强制关闭优酷后重新打开出现找不到路径，但是在.cache/winetricks/路径下可以找到优酷的安装信息

**Comment by hillwoodroc** [comment]
微信已修复。其他的我有空看看。

**Comment by Ericwyn** [comment]
sha256sum mismatch! Rename /home/user/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE and try again
今天安装的 TIM 的时候出现这个问题, 另外安装 QQ轻聊版 和 QQ 的时候也会出现这个问题, 只是提示的是那两个软件的 sha256sum 不匹配

**Comment by MukuroSama** [comment]
有道云笔记也这样了，求解决
