### ISSUE TITLE
能加入AUR吗？

### ISSUE THREAD

**Issue by swordfeng** [hillwoodroc/winetricks-zh#12]
毕竟AUR比较方便  
加入AUR并且被vote多的话是有可能引起上游注意的

**Comment by hillwoodroc** [comment]
呵呵，这个你应该去找 AUR 的维护者，我并不是 arch linux 社区的人。

**Comment by swordfeng** [comment]
AUR没有官方维护者啊，都是用户自己上传的

**Comment by hillwoodroc** [comment]
不熟悉 AUR 的流程，抱歉。
