### ISSUE TITLE
QQ轻聊版显示"QQ安全组件异常"

### ISSUE THREAD

**Issue by x86vk** [hillwoodroc/winetricks-zh#121]
如题，Arch Linux，使用wine 3.0 rc5

**Comment by hillwoodroc** [comment]
QQ安全组件有未经用户许可私自扫描磁盘文件的行为，本来就不是什么好东西，报错是好事，请忽视错误提示。这是禁用 wine 的模拟 windows 内核模块带来的副作用。

**Comment by x86vk** [comment]
Soga,但这样就没法启动了呀。。。
anyway，我转而用QQ了，发现`.desktop`文件里面如果直接写`Exec=env
WINEPREFIX=/home/hanjz/.local/share/wineprefixes/qq wine "C:\Program Files
(x86)/Tencent/QQ/bin/QQScLauncher.exe"`,kde就无法启动它。
只有再新建一个内容为`env WINEPREFIX=/home/hanjz/.local/share/wineprefixes/qq wine
'C:\Program Files
(x86)/Tencent/QQ/bin/QQScLauncher.exe'`的`.sh`文件，并让`Exec=<.sh的路径>`才能启动。不知道这个是不是只是我这边的问题。

Hillwood Yang <notifications@github.com>于2018年1月14日周日 下午10:28写道：
