### ISSUE TITLE
QQ音乐已经不能使用，请更新

### ISSUE THREAD

**Issue by Howard-00** [hillwoodroc/winetricks-zh#124]
安装后自动升级，然后就直接一片黑

**Comment by hillwoodroc** [comment]
没事别自己乱升级，新版本可用的话我早就升上去了。同理还有 QQ 。

Howard-00 <notifications@github.com> 于 2018年4月6日周五 08:14写道：

**Comment by hillwoodroc** [comment]
已升级。
