### ISSUE TITLE
QQ和TIM安全组件异常233333

### ISSUE THREAD

**Issue by amtlib-dot-dll** [hillwoodroc/winetricks-zh#125]
#26 #27 #59 #121 
Fedora 27 Wine-3.5
安装过程正常，运行失败，提示安全组件异常:joy: :joy:完全参照verb里面来的

**Comment by hillwoodroc** [comment]
不影响使用，我也不会去修这个问题。安全组件是 QQ 自带的恶意软件扫描组件，在 Linux 下也没必要用它。

**Comment by amtlib-dot-dll** [comment]
谢谢回复，我很久没用TIM和QQ了，不过我记得当时的现象时无法运行，强制推出，完全无法使用 :joy:
