### ISSUE TITLE
InstMsiW挂了。手动下载放进去没用重新下载。

### ISSUE THREAD

**Issue by peaceshi** [hillwoodroc/winetricks-zh#126]
正在解析主机 ftp.hp.com (ftp.hp.com)... 15.73.48.54, 15.72.188.125
正在连接 ftp.hp.com (ftp.hp.com)|15.73.48.54|:21... 已连接。
正在以 anonymous 登录 ... 登录成功！
==> SYST ... 完成。    ==> PWD ... 完成。
==> TYPE I ... 完成。  ==> CWD (1) /pub/softlib/software/msi ... 完成。
==> SIZE InstMsiW.exe ... 1822848
==> PASV ... 
服务器响应时发生错误，正在关闭控制连接。

**Comment by hillwoodroc** [comment]
已合并上游更新，再试试看。
