### ISSUE TITLE
qq tim不能运行

### ISSUE THREAD

**Issue by BBBob** [hillwoodroc/winetricks-zh#128]
在最新的wine 3.8-1中，qq和tim均不能运行
而在wine 3.7-1 中，这些都能正常运行
因为我只用了这俩软件，不排除其它软件在最新版wine上不能运行的问题
希望能够对此进行修复

**Comment by hillwoodroc** [comment]
更新 wine 后首次运行 wine windows 程序都会自动更新 wine 容器的配置文件，这个过程如果进行不完整就会出问题。所以建议通过 winetricks 删除 QQ TIM 的容器再重新安装。我这里是没有问题的。

**Comment by hillwoodroc** [comment]
又试了几遍，QQ 有这个问题，但是 TIM 正常。目前有解决办法，我先试试给上游加一个原生 dll 支持。

**Comment by hillwoodroc** [comment]
wine 3.7 以后的版本引入了新的 APi 似乎造成了 QQ TIM 都无法启动。你试试把 wine 降级到 3.7

**Comment by BBBob** [comment]
自提出这个问题后，wine已经降到3.7
一个月前，QQlight开始登录闪退，TIM正常
前天TIM自动更新了，更新后登录闪退
在想办法重装容器并禁用更新
