### ISSUE TITLE
WINE is wine, which is neither on the path nor an executable file

### ISSUE THREAD

**Issue by Jackroyal** [hillwoodroc/winetricks-zh#13]
本来我安装的wine是1.6版本,但是安装qqlite的时候,提示目录没有写权限 .根据这里issiue的提示,我升级wine到1.7.2,但是这时候,执行winetricks,就会提示这个
我是下源码包,编译安装的,64位系统,现在系统里面有wine64这个命令,没有wine这个命令.而且apt-get install 安装的wine,还是提示连环的依赖.难道我的wine没有安装成功???
WINE is wine, which is neither on the path nor an executable file

**Comment by hillwoodroc** [comment]
提示已经很明显了，系统路径里面找不到 wine ，说明安装有问题，你自己检查一下。另外，请保证 wine 的版本不低于 1.7.35。

**Comment by Jackroyal** [comment]
ok  我重新安装后，将wine升级到最新版了
qqlight已经成功安装上了，谢谢
不过不知道是不是我的有bug，右上角没有qq的图标，而且，我不知道哪里打开它，没有快捷方式
新手一枚，请多包涵

**Comment by hillwoodroc** [comment]
QQ 轻聊那个有问题，因为 wine 的 bug 无法创建快捷方式，所以你只能用 6.3 或者国际版了。有空我会把轻聊清理出去。

**Comment by Jackroyal** [comment]
恩恩 ，我发现用winetricks-zh里面带的那个qq.verb可用，有快捷方式
不过还是不完美，右上角没有通知图标，有时候按ctrl+alt+z，主界面不弹出，登录qq后，没有消息的情况下，都不能查看主面板。

**Comment by hillwoodroc** [comment]
不知道你用的什么桌面环境。

**Comment by Jackroyal** [comment]
ubuntu 14.04 lts     64位  
wine-1.7.38
winetricks 20140302

**Comment by hillwoodroc** [comment]
KDE Gnome 都没有这个问题，你应该给 Ubuntu 报个 bug.

**Comment by Jackroyal** [comment]
这是给wine报bug
还是给ubuntu官方报bug？

**Comment by hillwoodroc** [comment]
你先试试其他软件会不会出现在通知区域里面，如果能显示就给 wine 报，不能显示就给 Ubuntu 报。

**Comment by Endle** [comment]
我认为是 Gnome 3 的问题
请问 @Jackroyal  可以换一个桌面环境试试吗？
