### ISSUE TITLE
wechat sha256sum mismatch! 

### ISSUE THREAD

**Issue by WuXinyang2012** [hillwoodroc/winetricks-zh#130]
请更新下微信吧

另外，想问下我在使用winetricks-zh的时候，提示：
You are running winetricks-20171222-next, latest upstream is winetricks-20180603!

这个是什么回事呢？ 我从未安装过winetricks，直接用的库里的winetricks-zh。

Ubtuntu 18.04 LTS系统，安装的是官方源里的wine最新版： wine-stable 3.0.1
没有装winetricks

**Comment by hillwoodroc** [comment]
Fixed.
