### ISSUE TITLE
安装微信失败，无法下载安装文件

### ISSUE THREAD

**Issue by Twei1994** [hillwoodroc/winetricks-zh#131]
错误提示：
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

You are running winetricks-20171222-next, latest upstream is winetricks-20180603!

You should update using your distribution's package manager, --self-update, or manually.

------------下载微信安装包-------------------

Checksum for /home/work/.cache/winetricks/wechat/WeChatSetup.exe did not match, retrying download
------------------------------------------------------
Executing cd /home/work/.cache/winetricks/wechat

--2018-06-15 19:59:46--  (try: 3)  https://web.archive.org/web/2000/http://dldir1.qq.com/weixin/Windows/WeChatSetup.exe
Connecting to web.archive.org (web.archive.org)|8.7.198.45|:443... failed: Connection timed out.
Giving up.

------------------------------------------------------
Downloading https://web.archive.org/web/2000/http://dldir1.qq.com/weixin/Windows/WeChatSetup.exe failed
------------------------------------------------------
重复下载3次失败

**Comment by hillwoodroc** [comment]
Fixed.
