### ISSUE TITLE
微信的sha256sum mismatch 问题依旧

### ISSUE THREAD

**Issue by WuXinyang2012** [hillwoodroc/winetricks-zh#132]
确认不是我环境的问题，因为我试着安装了QQlgiht与evernote，都可以安装，唯独微信会报错..
我已checkout最新版，且已将/usr/bin里的winetricks-zh替换为新版了
nevermind，我还是决定用electron那个了，虽然简陋但是省事点...

**Comment by hillwoodroc** [comment]
已修复。检测 sha256sum 的本意是为了防止你下载到被黑客修改过的版本，但是鹅厂恶心的是，每次更新都采取直接替换原文件的方式，所以每次鹅厂更新都会造成 sha256sum 实效。如果你自己非常有把握，可以在脚本里面把 sha256sum 删掉，就不会再检查 sha256sum 了。

**Comment by isaac574** [comment]
我试一下。谢了。HILLWOODROC。
