### ISSUE TITLE
Verb脚本能不能优先用离线的？

### ISSUE THREAD

**Issue by ryanlycch** [hillwoodroc/winetricks-zh#133]
在安装微信时总是碰到sha256校验出错，手动把wechat.verb里的sha256sum改为下载的安装文件的sha256sum值还是提示错误，应该是在安装时自动到github上下载最新的verb文件了，所以本地改的无效。

能不能先检测本地有没有Verb文件，有的话就用本地的，没有的话再上网获取？

谢谢！

**Comment by hillwoodroc** [comment]
已修复。检测 sha256sum 的本意是为了防止你下载到被黑客修改过的版本，但是鹅厂恶心的是，每次更新都采取直接替换原文件的方式，所以每次鹅厂更新都会造成 sha256sum 失效。如果你自己非常有把握，可以在脚本里面把 sha256sum 删掉，就不会再检查 sha256sum 了。
如果可以，也希望每次 sha256sum 有变动时及时告诉我。我本人是不用 PC 端的微信的。
