### ISSUE TITLE
dll缺失导致TIM无法运行

### ISSUE THREAD

**Issue by skywet** [hillwoodroc/winetricks-zh#134]
运行时提示
module:import_dll Library libtcmalloc.dll (which is needed by L"C:\\Program Files (x86)\\Tencent\\TIM\\Bin\\TIM.exe") not found
Wine版本:wine 3.8

**Comment by hillwoodroc** [comment]
这不是致命问题，你把完整的 log 贴上来。

**Comment by skywet** [comment]
module:import_dll Library libtcmalloc.dll (which is needed by L"C:\Program Files (x86)\Tencent\TIM\Bin\TIM.exe") not found
0012:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
0012:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
000f:err:service:process_send_command service protocol error - failed to write pipe!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"MountMgr" failed to start: 1053
001b:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0021:fixme:advapi:RegisterEventSourceW ((null),L"QPCore"): stub
0021:fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000000,(nil),0x0001,0x00000000,0x73fc64,(nil)): stub
0021:fixme:advapi:DeregisterEventSource (0xcafe4242) stub
0024:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
0024:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
000f:err:service:process_send_command service protocol error - failed to write pipe!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"WineBus" failed to start: 1053
0009:fixme:msvcrt:_configure_wide_argv (1) stub
0009:fixme:msvcrt:_initialize_wide_environment stub
002a:err:module:attach_dlls "libtcmalloc.dll" failed to initialize, aborting
002a:err:module:attach_dlls Initializing dlls for L"C:\\Program Files (x86)\\Tencent\\TIM\\Bin\\TIM.exe" failed, status c0000005
0022:err:module:load_builtin_dll failed to load .so lib for builtin L"l3codeca.acm": libmpg123.so.0: 无法打开共享对象文件: 没有那个文件或目录
0022:fixme:ntdll:NtQueryInformationProcess (process=0xa8) Unimplemented information class: ProcessSessionInformation
002f:fixme:iphlpapi:NotifyAddrChange (Handle 0x182fed8, overlapped 0x182feb8): stub
002f:fixme:iphlpapi:CancelIPChangeNotify (overlapped 0x182feb8): stub
0022:fixme:process:WTSGetActiveConsoleSessionId stub
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84f468
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84f470
0022:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
0022:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0022:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x84f1e8 1 C) semi-stub
0022:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x84efc8 1 C) semi-stub
0022:err:rpc:I_RpcGetBuffer no binding
0022:fixme:crypt:CryptProtectMemory (0x166c10 112 00000001): stub
0022:fixme:crypt:CryptUnprotectMemory (0x10dc070 112 00000001): stub
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84c758
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84e90c
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84e934
0022:fixme:msvcrt:__clean_type_info_names_internal (0x1ba0454) stub
0022:fixme:msvcrt:__clean_type_info_names_internal (0x10116fb4) stub
0022:fixme:msvcrt:__clean_type_info_names_internal (0x3ce33c) stub
0021:fixme:advapi:RegisterEventSourceW ((null),L"QPCore"): stub
0021:fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000000,(nil),0x0001,0x00000000,0x73fc80,(nil)): stub
0021:fixme:advapi:DeregisterEventSource (0xcafe4242) stub
001b:fixme:msvcrt:__clean_type_info_names_internal (0x30283754) stub
001b:fixme:msvcrt:__clean_type_info_names_internal (0x3f34ec) stub
001b:fixme:msvcrt:__clean_type_info_names_internal (0x1101d33c) stub
001b:fixme:msvcrt:__clean_type_info_names_internal (0x11f1138c) stub
001b:fixme:msvcrt:__clean_type_info_names_internal (0x89fc34) stub
001b:fixme:msvcrt:__clean_type_info_names_internal (0x11114564) stub

**Comment by hillwoodroc** [comment]
你是用的 wayland 还是 xorg ？

**Comment by skywet** [comment]
xorg

**Comment by FateRover** [comment]
z这是ｗｉｎｅ的ｂｕｇ
