### ISSUE TITLE
如何避免微信校验出错次数

### ISSUE THREAD

**Issue by Twei1994** [hillwoodroc/winetricks-zh#135]
直接点击外链会导致崩溃，崩溃次数多了就提示下面的：
![image](https://user-images.githubusercontent.com/18332086/42017284-0cb2f12c-7ae1-11e8-9b8f-ae418154e832.png)
怎么解决外链崩溃或者避免这个检查呢？

**Comment by Twei1994** [comment]
或者怎么卸载？

**Comment by hsxsix** [comment]
我是使用的crossover，不过道理都差不多。
```
nano .cxoffice/WeChat/drive_c/users/crossover/Application Data/Tencent/WeChat/All Users/config/configEx.ini
```
编辑configEx.ini文件，将CrashCnt=5的 值改为小于5的值，比如1、-999、 -10000等等。
我比较关心的是截图发送文件这个问题怎么解决，知道的告诉我一声

**Comment by Twei1994** [comment]
我这里这个文件的目录是这个：
```
.local/share/wineprefixes/wechat/drive_c/users/work/Application Data/Tencent/WeChat/All Users/config
```
