### ISSUE TITLE
AliIM2016_taobao(8.60.01C).exe 这个文件已经没了

### ISSUE THREAD

**Issue by largewhale** [hillwoodroc/winetricks-zh#138]
AliIM2016_taobao(8.60.01C).exe 文件里的地址已经失效了吧，下载不到。网上搜了一下，也找不到这个版本的合适链接。怎么解？

**Comment by hillwoodroc** [comment]
这个版本其实也没法用了，新版跑起来又有严重问题。

**Comment by largewhale** [comment]
现在用9.12.05c，之前官网下的。淘宝网页上直接点选进入旺旺，还没有成功。其他常规的功能可以凑活用。了胜于无啊

**Comment by hillwoodroc** [comment]
已取消对旺旺的支持。
