### ISSUE TITLE
微信相关问题

### ISSUE THREAD

**Issue by Twei1994** [hillwoodroc/winetricks-zh#139]
1. 只能粘贴微信内的文本，不能截图，外部截图也无法粘贴；
2. 点击外链会crash；

**Comment by hillwoodroc** [comment]
不能截图的问题的确存在，其他问题无法重现。

**Comment by bigshans** [comment]
查看公众号历史消息和点击文章都会 crash ，会弹出一个窗口，随后就会崩溃。只能采取用浏览器的方式打开。

**Comment by hillwoodroc** [comment]
wine 5.4 已经修正了 crash 的问题。

**Comment by BBBob** [comment]
微信外的文本，如果带格式是粘不了的(比如网页上的内容，从typora复制出的内容等)，所以用vim或其他工具把格式去掉然后再粘就可以了。
我这里外部截图有时能粘有时不能粘，不能稳定复现，目前不知道是什么原因。

**Comment by hillwoodroc** [comment]
可能需要安装 wine Gecko

**Comment by shamefulCake1** [comment]
可以关闭吗？
