### ISSUE TITLE
QQ轻聊版更新了

### ISSUE THREAD

**Issue by TAXUEZJU** [hillwoodroc/winetricks-zh#14]
QQ发布了新的轻聊版，http://dldir1.qq.com/qqfile/qq/QQ7.3LightTrial/14248/QQ7.3LightTrial.exe
不过试了下，用原来的那些设置可以正常安装，但群文件打开就会崩溃，别的还没测试，不知道您能更新下verb文件吗

**Comment by hillwoodroc** [comment]
对于 QQ 6.3 （轻聊版）包括以上版本 wine 都存在创建快捷方式失败的 bug ，在 wine 官方修复这个 bug 前我是不会更新 QQ 以及轻聊版的。

**Comment by hillwoodroc** [comment]
已更新，采用手动安装启动文件绕过 bug 。没办法旧版 QQ 都被鹅厂给禁止了。
