### ISSUE TITLE
ubuntu18.04+wine4.0安装qq8.9退出后在无法打开，要重启机器后才可以

### ISSUE THREAD

**Issue by bodo005** [hillwoodroc/winetricks-zh#143]
QQ正常的，就是退出后不能打开，不知道是什么原因造成的。

**Comment by BBBob** [comment]
QQ退出后会有进程驻留导致下一次无法打开的情况，打不开使用这个脚本杀掉进程试一下。
```
#!/bin/sh
ps aux|grep -v grep|grep wine|cut -c 9-15|xargs kill 
ps aux|grep -v grep|grep QQ|cut -c 9-15|xargs kill 
ps aux|grep -v grep|grep qq|cut -c 9-15|xargs kill 
pkill  plugplay.exe
pkill  explorer.exe
pkill  services.exe
```

**Comment by bodo005** [comment]
> QQ退出后会有进程驻留导致下一次无法打开的情况，打不开使用这个脚本杀掉进程试一下。
> 
> ```
> #!/bin/sh
> ps aux|grep -v grep|grep wine|cut -c 9-15|xargs kill 
> ps aux|grep -v grep|grep QQ|cut -c 9-15|xargs kill 
> ps aux|grep -v grep|grep qq|cut -c 9-15|xargs kill 
> pkill  plugplay.exe
> pkill  explorer.exe
> pkill  services.exe
> ```

d

> QQ退出后会有进程驻留导致下一次无法打开的情况，打不开使用这个脚本杀掉进程试一下。
> 
> ```
> #!/bin/sh
> ps aux|grep -v grep|grep wine|cut -c 9-15|xargs kill 
> ps aux|grep -v grep|grep QQ|cut -c 9-15|xargs kill 
> ps aux|grep -v grep|grep qq|cut -c 9-15|xargs kill 
> pkill  plugplay.exe
> pkill  explorer.exe
> pkill  services.exe
> ```

可以了，暂时只能用脚本杀了。另外我测试了微信，微信没有这个问题

**Comment by hillwoodroc** [comment]
杀 QQ 进程请用：
`env WINEPREFIX=/home/pc/.local/share/wineprefixes/qq wineserver -k`

**Comment by bodo005** [comment]
> 杀 QQ 进程请用：
> `env WINEPREFIX=/home/pc/.local/share/wineprefixes/qq wineserver -k`

最新补充，我把之前手动安装的gecko的删了，也在容器里把qq删了，然后重新安装了一遍qq，自动安装的gecko，qq空间，邮箱才能通过ie打开，手动安装的gecko不行会假死，必须要自动安装，最后qq能够正常退出了。

**Comment by bodo005** [comment]
> 杀 QQ 进程请用：
> `env WINEPREFIX=/home/pc/.local/share/wineprefixes/qq wineserver -k`

试了下，这条命令也有用。各位大过节的春节快乐！
