### ISSUE TITLE
安装TIM失败,服务正常下载TIM.tar.gz 

### ISSUE THREAD

**Issue by artiechan** [hillwoodroc/winetricks-zh#144]
我尝试安装Tim，可是总是提示：sha256sum mismatch! Rename /home/..../.cache/winetricks/tim/TIM.tar.gz and try again.

**Comment by hillwoodroc** [comment]
服务器宕了三天，已经恢复了。

**Comment by artiechan** [comment]
今天试了，还是一样的。

**Comment by hillwoodroc** [comment]
你再试试看。
