### ISSUE TITLE
微信新消息没有提醒

### ISSUE THREAD

**Issue by Frefreak** [hillwoodroc/winetricks-zh#147]
有新消息不闪也没有红点之类的，点开system tray的图标才能看到，这是个已知的问题吗？搜了下好像没看到说这个的
archlinux，KDE

**Comment by hillwoodroc** [comment]
是有这个问题，可能是 wine 的 api 没有实现这个功能。

**Comment by hillwoodroc** [comment]
红点是没有，但是会闪。

**Comment by BBBob** [comment]
archlinux在kde上确实不会闪烁，在i3wm上是正常的，可能是最新版kde消息通知接口的问题。另外gnome上也不能闪烁了。不知道为什么i3wm上一切正常。
