### ISSUE TITLE
w_call fakechinese出现404

### ISSUE THREAD

**Issue by diabloneo** [hillwoodroc/winetricks-zh#15]
Executing w_do_call fakechinese
Executing load_fakechinese
Executing w_do_call wenquanyi
Executing load_wenquanyi
Executing mkdir -p /home/diabloneo/.cache/winetricks/wenquanyi
Downloading http://downloads.sourceforge.net/wqy/wqy-microhei-0.2.0-beta.tar.gz to /home/diabloneo/.cache/winetricks/wenquanyi
--2015-07-19 12:10:25--  http://downloads.sourceforge.net/wqy/wqy-microhei-0.2.0-beta.tar.gz
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-19 12:10:29 ERROR 404: Not Found.

**Comment by Endle** [comment]
我这里测试没有问题
可能是你所在的网络环境导致的

**Comment by hillwoodroc** [comment]
昨天 sourceforge 有些抽风，现在已恢复正常。
