### ISSUE TITLE
微信又更新了

### ISSUE THREAD

**Issue by kooritea** [hillwoodroc/winetricks-zh#151]
这个sha256sum是怎样算出来的
我直接
```bash
sha256sum -b /path/WeChatSetup.exe
// acf0415cb252e788f8b53ddaba41d4e984dad9435ef581bc027a8f5823f03e1f
```
还是sha256sum mismatch!

删除verb里面的hash依然是sha256sum mismatch!

**Comment by kooritea** [comment]
直接在776行检查hash的方法加个return绕过去了...

**Comment by hillwoodroc** [comment]
Fixed on https://github.com/hillwoodroc/winetricks-zh/commit/f127a0d40ef643651a1fe61577f824735a27a093
