### ISSUE TITLE
你好，winetricks可以使用命令来安装软件么？

### ISSUE THREAD

**Issue by fgheng** [hillwoodroc/winetricks-zh#153]
不知道winetrick可不可以直接使用命令行进行软件安装呢？比如winetricks install wechat这样而不需用打开界面。我这里界面开启太慢了。

**Comment by weearc** [comment]
请使用winetricks-zh [verb]指令。如安装tim，winetricks-zh tim


 
---原始邮件---
发件人: "NULL"<notifications@github.com&gt;
发送时间: 2020年2月21日 20:51:51
收件人: "hillwoodroc/winetricks-zh"<winetricks-zh@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hillwoodroc/winetricks-zh] 你好，winetricks可以使用命令来安装软件么？ (#153)



不知道winetrick可不可以直接使用命令行进行软件安装呢？比如winetricks install wechat这样而不需用打开界面。我这里界面开启太慢了。

**Comment by fgheng** [comment]
了解了，谢谢您
