### ISSUE TITLE
微信无法输入

### ISSUE THREAD

**Issue by fgheng** [hillwoodroc/winetricks-zh#154]
使用wintricks-zh wechat安装的微信，打开之后无法在输入框输入任何内容，可以说是不显示内容但是可以发送内容，鼠标划过输入框的时候提示`fixme:richedit:fnTextSrv_OnTxSetCursor 0ACB74C8: STUB`
archlinux，wine使用的是wine-stagging 5.2版本

**Comment by fgheng** [comment]
如果使用riched20的native then build，那么扫码之后微信就会启动失败，如果不用native then build 而是用build then native的话，扫码后可以启动微信但是无法输入

**Comment by hillwoodroc** [comment]
wine 5.2 无法重现。
