### ISSUE TITLE
运行错误“~/usr/bin/winetricks-zh: 15553: Syntax error: "}" unexpected~”

### ISSUE THREAD

**Issue by Hoking007** [hillwoodroc/winetricks-zh#157]
运行错误“~/usr/bin/winetricks-zh: 15553: Syntax error: "}" unexpected~”

**Comment by hillwoodroc** [comment]
Fixed in https://github.com/hillwoodroc/winetricks-zh/commit/9b3f1dae0b22cb421a3fad925cb8bbef08aec705
