### ISSUE TITLE
安装QQ音乐失败，校验码错误

### ISSUE THREAD

**Issue by Hoking007** [hillwoodroc/winetricks-zh#158]
$ winetricks-zh qqmusic
......
sha256sum mismatch! Rename /home/hoking/.cache/winetricks/qqmusic/QQMusicSetup.exe and try again.

试过很多次都是如此，因为买了QQ音乐会员，很多歌只在这里面
还是希望能够装起来，还请作者帮忙看看

**Comment by hillwoodroc** [comment]
更新 sha256sum，你试试看能不能用。

**Comment by Hoking007** [comment]
> 更新 sha256sum，你试试看能不能用。

1, 检查下载的sha256sum
$ sha256sum /home/hoking/.cache/winetricks/qqmusic/QQMusicSetup.exe
6c181eb37d91edb7788b2d3dd5f2891a6fa4c3a607317ae8c3cd75f85cf3358c  /home/hoking/.cache/winetricks/qqmusic/QQMusicSetup.exe

2, 更新verb
将6c181eb37d91edb7788b2d3dd5f2891a6fa4c3a607317ae8c3cd75f85cf3358c更新到"verb/qqmusic.verb"并重新make install

3, 检查verb
$ cat /usr/share/winetricks-zh/qqmusic.verb
w_download https://dldir1.qq.com/music/clntupate/QQMusicSetup.exe 6c181eb37d91edb7788b2d3dd5f2891a6fa4c3a607317ae8c3cd75f85cf3358c

4, 重新运行winetricks-zh qqmusic依然提示校验码错误
$ winetricks-zh qqmusic
......
------------------------------------------------------
sha256sum mismatch! Rename /home/hoking/.cache/winetricks/qqmusic/QQMusicSetup.exe and try again.
------------------------------------------------------

**Comment by Hoking007** [comment]
> 更新 sha256sum，你试试看能不能用。

已解决！谢谢作者！

**Comment by Sciroccogti** [comment]
QQ音乐好像又更新了，校验码又不对了2333
