### ISSUE TITLE
QQ音乐可以正常安装，不过无法运行

### ISSUE THREAD

**Issue by Hoking007** [hillwoodroc/winetricks-zh#159]
QQ音乐可以正常安装，不过无法运行
wine: 5.0
os: ubuntu 20.04
请帮忙看看，谢谢！

**Comment by hillwoodroc** [comment]
在 winecfg 里面把 windows 的版本设置为 xp 就行了。下个版本我直接写在配置文件里面。

**Comment by Hoking007** [comment]
收到，改成xp就可以了，非常感谢！

**Comment by hillwoodroc** [comment]
Fixed in https://github.com/hillwoodroc/winetricks-zh/commit/d59e09bef12281b56904e2b8ba646bd70b17d202
