### ISSUE TITLE
运行regedit时总是失败，而winetricks不会报错

### ISSUE THREAD

**Issue by remyxo** [hillwoodroc/winetricks-zh#160]
安装组件或应用时，在运行regedit时总是失败，报找不到文件: '' , 而winetricks不会报错。看了一下脚本，winetricks-zh调用：
w_try "$WINE_MULTI" $cmdc regedit "$W_UNATTENDED_SLASH_S" "$@"
而winetricks调用：
w_try "$WINE_MULTI" $cmdc regedit ${W_OPT_UNATTENDED:+/S} "$@"

环境：ElementaryOS 5.1.3 （基于Ubuntu 18.04 LTS）
Wine：5.0
同winetricks一样，将winetricks-zh部署在/usr/bin/下面。

**Comment by hillwoodroc** [comment]
你再试试新版本，我更新了一下。

**Comment by remyxo** [comment]
已OK。
对话框是否可以改一下，ubuntu下显示对话框是调用zenity，如果不加--width=450, 对话框一个竖的长条，很不美观，加上--width，对话框就正常了。我在winetricks项目下也提了这个问题。

**Comment by hillwoodroc** [comment]
这个问题只能看上游的意见了。
