### ISSUE TITLE
微信的sha256sum值不对

### ISSUE THREAD

**Issue by remyxo** [hillwoodroc/winetricks-zh#161]
4eb7fda85532da96b8cb9ddb27b1fcf5f1536b47b1d2ff762dd882fc4e597f06  WeChat_C1018.exe
估计程序有更新。
脚本中的sha256sum为：
404370f1ab66abd3601fe19415b805effaa033d76f32e911743d2e12644b898b
请更新。

**Comment by hillwoodroc** [comment]
Fixed in https://github.com/hillwoodroc/winetricks-zh/commit/eb488d5bf4430816bd775885257d0d6a517fda4c

**Comment by isaac574** [comment]
我也遇到相同的问题，尽管我已改了SHA256SUM的值。
现将代码拷贝如下：
Running Wine/winetricks as root is highly discouraged. See https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F
------------------------------------------------------
Executing mkdir -p /root
Using winetricks 20200412-next - sha256sum: 33511e5ad9d909ea84cbca77fcfe5813fdaef2ac20645a089fc5e8a6f75eb44d with wine-5.0.2 and WINEARCH=win32
winetricks GUI enabled, using zenity 3.32.0
Executing w_do_call wechat
Executing mkdir -p /root
Executing load_wechat 
Executing mkdir -p /root/.cache/winetricks/wechat
Executing cd /root/.cache/winetricks/wechat
Downloading https://dldir1.qq.com/weixin/Windows/WeChat_C1018.exe to /root/.cache/winetricks/wechat
Executing cd /home/isaacsheng/下载/winetricks-zh-20200421.3
------------------------------------------------------
绕过 wine bug 38038 -- Installing native riched20 to work around typing bug
------------------------------------------------------
Executing w_do_call riched20
Executing mkdir -p /root
Executing load_riched20 
Executing mkdir -p /root/.cache/winetricks/win2ksp4
Executing cd /root/.cache/winetricks/win2ksp4
Downloading https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE to /root/.cache/winetricks/win2ksp4
Executing cd /home/isaacsheng/下载/winetricks-zh-20200421.3
------------------------------------------------------
sha256sum mismatch! Rename /root/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE and try again.

不知有哪位高手能提携我一下？不胜感激！
