### ISSUE TITLE
微信启动后，如果其他程序界面在前面，则会有微信窗口的阴影，其他运行正常。

### ISSUE THREAD

**Issue by remyxo** [hillwoodroc/winetricks-zh#162]
微信启动后，如果其他程序界面激活到前面，则会有微信窗口的阴影，其他运行正常。

![屏幕截图 2020-05-04 12 37 27](https://user-images.githubusercontent.com/37561550/80936558-42cd8500-8e04-11ea-9520-04396c0b7f24.png)
![屏幕截图 2020-05-04 12 36 13](https://user-images.githubusercontent.com/37561550/80936565-4a8d2980-8e04-11ea-87ca-f64d59833338.png)

**Comment by 12101111** [comment]
这是微信自己绘制的阴影，我曾经试着在X这一层隐藏掉，但是没找到什么好的办法。
倒是有人在win32这一层隐藏掉了这个阴影： https://blog.kangkang.org/index.php/archives/397

**Comment by hillwoodroc** [comment]
这是 wine 处理微信阴影效果的机制问题，请向 wine 官方反应，我这里不处理。
