### ISSUE TITLE
Wechat Check sum incorrect due to update in remote

### ISSUE THREAD

**Issue by qqpp4130** [hillwoodroc/winetricks-zh#163]
The sum check mismatched. used: b20df18ee04ebd9246ad3ab45b4e7012c1f9a569e53b035b204206047ec25e56

New one:
973b429c4f9c1882340c3b8bfa066ae159b5dd409f876538e3820efbeb0a5ab4

**Comment by hillwoodroc** [comment]
Fixed in https://github.com/hillwoodroc/winetricks-zh/commit/743a4e9e594f345ede3c5c5325ddc278e66c8070
