### ISSUE TITLE
winetricks-zh不需要isolate参数是如何实现的？

### ISSUE THREAD

**Issue by WaterFloat** [hillwoodroc/winetricks-zh#166]
winetricks-zh 默认将应用安装到单独容器，不需要isolate参数，请问是如何实现的？

**Comment by hillwoodroc** [comment]
![2020-06-29 16-48-48 的屏幕截图](https://user-images.githubusercontent.com/1880237/85993344-c8e30200-ba28-11ea-8c0a-b2de6a7bf59c.png)
