### ISSUE TITLE
在POP OS下（20.10版本）安装WECHAT总是出现SHA256SUM的值不匹配。

### ISSUE THREAD

**Issue by isaac574** [hillwoodroc/winetricks-zh#169]
我也遇到相同的问题，尽管我已改了SHA256SUM的值。
再次尝试将这个值去掉，还是没用场。
现将代码拷贝如下：
Running Wine/winetricks as root is highly discouraged. See https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F
Executing mkdir -p /root
Using winetricks 20200412-next - sha256sum: 33511e5ad9d909ea84cbca77fcfe5813fdaef2ac20645a089fc5e8a6f75eb44d with wine-5.0.2 and WINEARCH=win32
winetricks GUI enabled, using zenity 3.32.0
Executing w_do_call wechat
Executing mkdir -p /root
Executing load_wechat
Executing mkdir -p /root/.cache/winetricks/wechat
Executing cd /root/.cache/winetricks/wechat
Downloading https://dldir1.qq.com/weixin/Windows/WeChat_C1018.exe to /root/.cache/winetricks/wechat
Executing cd /home/isaacsheng/下载/winetricks-zh-20200421.3
绕过 wine bug 38038 -- Installing native riched20 to work around typing bug
Executing w_do_call riched20
Executing mkdir -p /root
Executing load_riched20
Executing mkdir -p /root/.cache/winetricks/win2ksp4
Executing cd /root/.cache/winetricks/win2ksp4
Downloading https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE to /root/.cache/winetricks/win2ksp4
Executing cd /home/isaacsheng/下载/winetricks-zh-20200421.3
sha256sum mismatch! Rename /root/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE and try again.

不知有哪位高手能提携我一下？不胜感激！

**Comment by hillwoodroc** [comment]
Fixed by https://github.com/hillwoodroc/winetricks-zh/commit/1b8ee109e9cc646b7436b82d4318fd3edfe3fcc8
