### ISSUE TITLE
QQ 不能“记住密码”的问题

### ISSUE THREAD

**Issue by yh-liu** [hillwoodroc/winetricks-zh#172]
我看“已知问题“ 那有说明
不能保存密码（若需启用保存密码功能，可以在 winecfg 中启用 txplatform.exe，不过这样QQ、TIM 不能完全退出）

我用winecfg启用了txplatform.exe（原装），启动发现能记住密码了，一切正常了，当时很窃喜。
后来为了测试，到设置中将记住的密码取消了，重新登录，选中记住密码自动登录，然后再退出，再登录，发现又不能记住密码了，而且这次无论怎么尝试，还是无法记住密码。太抓狂了！
能帮忙看看怎么回事吗？谢谢

**Comment by yh-liu** [comment]
补充一句，wine用的是5.0.3稳定版，32bit

**Comment by hillwoodroc** [comment]
既然我都把 txplatform.exe 禁用了，那么开启后造成的问题就不在我解决范围内了。
