### ISSUE TITLE
winxpsp3 可以从微软官网下载

### ISSUE THREAD

**Issue by SamLukeYes** [hillwoodroc/winetricks-zh#173]
链接：http://www.download.windowsupdate.com/msdownload/update/software/dflt/2008/04/windowsxp-kb936929-sp3-x86-enu_c81472f7eeea2eca421e116cd4c03e2300ebfde4.exe
不知道为什么 winetricks 为什么要改用 gnome 的 ftp 下载，那个链接不搭梯子访问不了

**Comment by hillwoodroc** [comment]
Fixed in https://github.com/hillwoodroc/winetricks-zh/commit/ff0d8e7aa18f38a3a0cdaa86622ade91fcd03b9a
