### ISSUE TITLE
安装路径无效，您没有权限在此位置写入数据，请重新选择

### ISSUE THREAD

**Issue by dispensable** [hillwoodroc/winetricks-zh#2]
喜闻乐见，之前直接winetricks TMP2的时候也是这个提示，不知有什么解决方法？
fixme:wincodecs:PngDecoder_Block_GetCount 0x42125c0,0x33edf8: stub
[62:49:0207/233943:12541693:INFO:check_path.cpp(405)] Delete file :C:\Program Files (x86)\qqtest , failed with 3
fixme:wincodecs:PngDecoder_Block_GetCount 0x4489998,0x33ee58: stub

**Comment by hillwoodroc** [comment]
你的 wine 版本太旧了，请升级先。1.7.30 以后的没问题，之前的版本就不太清楚是从哪个版本开始修复这个 bug 的了。这个不是 winetricks 的问题，我就关闭这个 issues 了，在 readme 里面我也写到过，请想办法升级到最新版本。

**Comment by dispensable** [comment]
好  本来就是想体验下，懒得搞了都。
多谢回复
