### ISSUE TITLE
 印象笔记 could not connect to server

### ISSUE THREAD

**Issue by shiliang-hust** [hillwoodroc/winetricks-zh#21]
evernote 提示could not connect to server
部分日志：
fixme:nls:GetUserPreferredUILanguages stub: 8 0x32fc48 (nil) 0x32fc44
fixme:msg:ChangeWindowMessageFilter 4a 00000001
fixme:msg:ChangeWindowMessageFilter c046 00000001
fixme:msg:ChangeWindowMessageFilter c044 00000001
fixme:msg:ChangeWindowMessageFilter c048 00000001
fixme:msg:ChangeWindowMessageFilter c047 00000001
err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow The explorer process failed to start.
fixme:ntdll:NtQueryInformationProcess (process=0xbc) Unimplemented information class: ProcessSessionInformation
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:iphlpapi:NotifyAddrChange (Handle 0x318040, overlapped 0x3a60c28): stub
fixme:winsock:WSALookupServiceBeginW (0x3180ec 0x00000ff0 0x318128) Stub!
[1201/194252:ERROR:network_change_notifier_win.cc(111)] WSALookupServiceBegin failed with: 8
fixme:ras:RasEnumConnectionsW (0x13eea0,0x515db04,0x76c623e4),stub!
fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
fixme:service:svcctl_EnumServicesStatusW resume index not supported
fixme:ras:RasEnumEntriesW ((nil),(null),0x1a3d58,0x515e334,0x17a3cc),stub!
fixme:shell:SetCurrentProcessExplicitAppUserModelID L"Evernote.Evernote.Client.5": stub
err:ole:CoGetClassObject class {77f10cf0-3db5-4966-b520-b7c54fd35ed6} not registered
err:ole:CoGetClassObject no class object {77f10cf0-3db5-4966-b520-b7c54fd35ed6} could be created for context 0x1
fixme:nls:GetUserPreferredUILanguages stub: 8 0x317e84 (nil) 0x317e80
fixme:msg:ChangeWindowMessageFilter 4a 00000001
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
err:secur32:schan_AcquireClientCredentials Could not find matching protocol

**Comment by hillwoodroc** [comment]
无法重现你的问题，请报上的 wine 版本号。

**Comment by shiliang-hust** [comment]
wine-1.8-rc3

**Comment by hillwoodroc** [comment]
1.8 rc3 无法重现。
