### ISSUE TITLE
QQ安全组件异常

### ISSUE THREAD

**Issue by Endle** [hillwoodroc/winetricks-zh#26]
安装后，运行 `wine QQ.exe` 出现提示

![2015-12-26 09-55-18](https://cloud.githubusercontent.com/assets/3221521/12004843/d8a6eba0-abb6-11e5-8b44-fb5222725c7f.png)

禁用 QQSafeUD.exe 与 QQExternal.exe 并不能解决问题
请问其他人能重现这个 bug 吗？

**Comment by hillwoodroc** [comment]
昨天晚上我更新了下，你用的是最新版本？
2015年12月26日 09:58，"Zhenbo Li" <notifications@github.com>写道：

**Comment by Endle** [comment]
wine --version
wine-1.8-121-g6767ac4

winetricks-zh 的最后一次 commit
commit ae55ae99ad76563142865be5675b1572c50b994f
Author: hillwood <hillwoodroc@gmail.com>
Date:   Sun Dec 20 21:51:08 2015 +0800

    Fix issues#25

我更新到了
commit 6c7b8f08d64f071d6cc01d6505cf34c132e9dc70
Author: hillwood <hillwoodroc@gmail.com>
Date:   Fri Dec 25 21:16:46 2015 +0800

    Merge changs from upstream, Set WINETRICKS_OPT_SHAREDPREFIX=0 as default.

问题解决，谢谢
