### ISSUE TITLE
退出qq后无法启动。

### ISSUE THREAD

**Issue by cz726894926** [hillwoodroc/winetricks-zh#27]
wine1.8
qq7.9
重启后显示安全组件错异常.
错误码：0x00008c02

**Comment by hillwoodroc** [comment]
在任务管理器里面杀死所有 wine 的进程后再打开试试。
2015年12月28日 22:03，"cz726894926" <notifications@github.com>写道：

**Comment by cz726894926** [comment]
我想我并不会用winetricks-zh来启动qq。直接wine qq不会加载设置，而且我也找不到启动qq的快捷方式。

**Comment by hillwoodroc** [comment]
直接用 wine 安装 QQ 不会自动生成快捷方式，这是 wine 的 bug 导致的。只有 winetricks 才能为 QQ 创建快捷方式，不然你只能手动创建了。

**Comment by cz726894926** [comment]
现在的情况是：我用winetricks-zh 安装了qq，而且安装结束后qq自动启动，能用。但是之后我进入/home/crona/.local/share/wineprefixes/qq/drive_c/Program Files/Tencent/QQ/Bin用wine windows program loader 打开却出现了问题，而且我直接打开config和用winetricks-zh启动的config设置是不一样的。

**Comment by hillwoodroc** [comment]
这样运行才对：
env WINEPREFIX=/home/crona/.local/share/wineprefixes/qq wine
"C:\Program Files\Tencent\QQ\bin\QQScLauncher.exe"

在 2015-12-28一的 21:21 -0800，cz726894926写道：

**Comment by cz726894926** [comment]
非常感谢能够为我这样的小白解决问题。

**Comment by hillwoodroc** [comment]
程序菜单里面有 QQ 的快捷方式，你根本不用通过命令行启动，除非是为了调试排错。

**Comment by fuxkak** [comment]
特别注册账号来感谢你们！

**Comment by fuxkak** [comment]
聊天窗口好友昵称是口口口怎么搞？打字框/聊天记录/好友列表的字都正常。另外，wine1.7.55+qq轻聊版or7.9都无法通过快捷方式和qq.exe启动，我把env WINEPREFIX=/home/crona/.local/share/wineprefixes/qq wine "C:\Program Files\Tencent\QQ\bin\QQScLauncher.exe"添加到了桌面启动器，现在启动正常了

**Comment by fuxkak** [comment]
网易云音乐运行正常，但是没有声音，在winetricks里的winecfg测试声音也没声音，该怎么解决呢？

**Comment by hillwoodroc** [comment]
在网易云音乐的设置里面更改一下输出设备。

**Comment by hillwoodroc** [comment]
口口口那个问题将 wine 升级到 1.8 以上版本可以修复。

**Comment by Endle** [comment]
无法显示昵称的话，也可以试试将 LANG 设置为 zh_CN.utf8

**Comment by fuxkak** [comment]
试过了，但没有待选项，改不了

在 2015年12月31日 21:00, Hillwood Yang 写道:

**Comment by hillwoodroc** [comment]
如果你是 64 位系统，请检查是否安装有 32 位的 alsa 和 pulseaudio 的库。

fuxkak <notifications@github.com>于2016年1月4日周一 11:14写道：

> 试过了，但没有待选项，改不了
>
> 在 2015年12月31日 21:00, Hillwood Yang 写道:
> >
> > 在网易云音乐的设置里面更改一下输出设备。
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/hillwoodroc/winetricks-zh/issues/27#issuecomment-168191169
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hillwoodroc/winetricks-zh/issues/27#issuecomment-168570810>
> .
>
-- 

Hillwood Yang
http://hillwoodhome.net
openSUSE member
hillwood@openSUSE.org

**Comment by fuxkak** [comment]
我是32位哦～Linux Mint 17.3

在 2016年01月04日 11:30, Hillwood Yang 写道:
