### ISSUE TITLE
qqlight 轻聊版,生成desktop的时候\bin出现乱码导致快捷方式没法用了.我也不知道如何修复...

### ISSUE THREAD

**Issue by jiagoumengxiang** [hillwoodroc/winetricks-zh#28]
rt
我是直接打开生成后的文件该好的,但是verb文件就不知道怎么改了...

**Comment by hillwoodroc** [comment]
你是说的开始菜单里面的启动器不能用还是什么其他问题？

zhangchen <notifications@github.com>于2015年12月30日周三 13:17写道：

> rt
> 我是直接打开生成后的文件该好的,但是verb文件就不知道怎么改了
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hillwoodroc/winetricks-zh/issues/28>.
>
-- 

Hillwood Yang
http://hillwoodhome.net
openSUSE member
hillwood@openSUSE.org
