### ISSUE TITLE
qq最小化之后怎么调出

### ISSUE THREAD

**Issue by weiyf** [hillwoodroc/winetricks-zh#29]
你好, 我想问一下qq最小化之后怎么调出?

**Comment by fuxkak** [comment]
运行命令是env WINEPREFIX=/home/fuxkak/.local/share/wineprefixes/qq wine "C:\Program Files\Tencent\QQ\bin\QQScLauncher.exe"   路径改成你自己的。最小化后怎么调出的问题，你应该是使用了ubuntu15.10吧？是unity不兼容造成的，ubuntu我不太了解，你查一下能否更换为其他桌面。

**Comment by weiyf** [comment]
我换成了ubuntu14.04还是出现这个问题, 最小化就找不到了, 其他桌面是用什么桌面?

**Comment by fuxkak** [comment]
你换系统可以这么轻松吗…你可以试试Linux Mint 他的桌面兼容wineQQ

在 2016年01月05日 08:48, weiyf 写道:

**Comment by hillwoodroc** [comment]
应该是 unity 更改了通知区域的接口 wine 没有及时支持，楼主可以到 wine 的官方报 bug 。
