### ISSUE TITLE
微信 for Windows 可以加进去吗？

### ISSUE THREAD

**Issue by tonghuix** [hillwoodroc/winetricks-zh#3]
下载 http://dldir1.qq.com/weixin/Windows/WeChat1.0_Beta.exe

我不熟悉verb文件怎么写，很想直接发PR的

**Comment by hillwoodroc** [comment]
你可以直接告诉我需要先用 winetricks 安装那些运行库，我写上去就行了。我自己试过，发现表情无法显示，目前没找到解决办法。

**Comment by zhubenwuzui** [comment]
请问字体怎么解决？我直接用wine安装微信，发现所有中文字体都是框框

**Comment by Endle** [comment]
winetricks cjkfonts 应该就足以解决字体了吧

**Comment by zhubenwuzui** [comment]
Downloading http://launchpad.net/takao-fonts/003.02/003.02.01/+download/takao-fonts-ttf-003.02.01.zip to /home/lida/.cache/winetricks/takao
--2015-08-18 13:23:49--  http://launchpad.net/takao-fonts/003.02/003.02.01/+download/takao-fonts-ttf-003.02.01.zip
Resolving launchpad.net (launchpad.net)... 91.189.89.223, 91.189.89.222
Connecting to launchpad.net (launchpad.net)|91.189.89.223|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-08-18 13:23:57 ERROR 404: Not Found.

------------------------------------------------------
Downloading http://launchpad.net/takao-fonts/003.02/003.02.01/+download/takao-fonts-ttf-003.02.01.zip failed
------------------------------------------------------

好像这个地址失效了。。。

**Comment by zhubenwuzui** [comment]
更新一下winetricks脚本就行了， 地址：
https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

**Comment by CodeFalling** [comment]
微信的输入框现在还有bug，`winetricks riched20`后可以看见输入框和正常输入英文，中文输入不行。
https://bugs.winehq.org/show_bug.cgi?id=38081

**Comment by xulz** [comment]
现在输入可以了.
如果显示方块字,也可能是你用的英文系统.我换成中文系统就没问题了.
如果有问题先执行    `winetricks riched20`
如果下载W2KSP4_EN.EXE失败,需要先[手动下载](http://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE)然后执行 `cp W2KSP4_EN.EXE ~/.cache/winetricks/win2ksp4`再执行上面的命令

**Comment by hillwoodroc** [comment]
已加入支持。
