### ISSUE TITLE
ArchLinux 迅雷闪退

### ISSUE THREAD

**Issue by shiliang-hust** [hillwoodroc/winetricks-zh#31]
在64位ArchLinux中，32位和64位的wine中，迅雷都会闪退，64位Evernote无法联网，32位正常
迅雷是不是还需要在系统中安装一些库？

**Comment by hillwoodroc** [comment]
清贴上完整的输出日志。
我这里只要不调整窗口大小，运行还是比较正常。

**Comment by hillwoodroc** [comment]
是有很大的问题，已取消对迅雷的支持。
