### ISSUE TITLE
QQ运行一段时间后报错重启

### ISSUE THREAD

**Issue by 329379172** [hillwoodroc/winetricks-zh#32]
centos7
wine-1.7.33

QQ8.0
 
fixme:ras:RasEnumConnectionsW (0xaaeb2c8,0xaaeb26c,0xaaeb270),stub!
fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
fixme:crypt:SystemFunction041 (0x2fd7868, 1090, 1): stub [RtlDecryptMemory]
fixme:crypt:SystemFunction040 (0x2fbf8d0, 1090, 1): stub [RtlEncryptMemory]
fixme:crypt:SystemFunction041 (0x2fd7868, 1090, 1): stub [RtlDecryptMemory]
fixme:crypt:SystemFunction040 (0x2fbf8d0, 1090, 1): stub [RtlEncryptMemory]
fixme:crypt:SystemFunction041 (0x2fd7868, 1090, 1): stub [RtlDecryptMemory]
fixme:crypt:SystemFunction041 (0x2fd7868, 1090, 1): stub [RtlDecryptMemory]
fixme:crypt:SystemFunction040 (0x2fbf8d0, 1090, 1): stub [RtlEncryptMemory]
fixme:file:MoveFileWithProgressW MOVEFILE_WRITE_THROUGH unimplemented
fixme:ras:RasEnumConnectionsW (0x34cb2c8,0x34cb26c,0x34cb270),stub!
fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
fixme:file:MoveFileWithProgressW MOVEFILE_WRITE_THROUGH unimplemented
fixme:wininet:InternetSetOptionW INTERNET_OPTION_SEND/RECEIVE_TIMEOUT/DATA_SEND_TIMEOUT 10
fixme:heap:HeapSetInformation (nil) 1 (nil) 0
fixme:dbghelp_dwarf:compute_location Only supporting one reg (edi/24 -> -2)
fixme:dbghelp_dwarf:compute_location Only supporting one reg (edi/24 -> -2)
fixme:dbghelp_dwarf:compute_location Only supporting one reg (edi/24 -> -2)
fixme:dbghelp_dwarf:dwarf2_parse_variable Unsupported constant (parameter) pEncodePara in function
fixme:dbghelp_dwarf:dwarf2_parse_variable Unsupported constant (parameter) dwFlags in function
fixme:resource:GetGuiResources (0xf5c,0): stub
fixme:dbghelp:elf_search_auxv can't find symbol in module
fixme:msvcrt:__clean_type_info_names_internal (0x51d57414) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5584d4f4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50dcb38c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5633c3a4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50d5408c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5578c464) stub
fixme:msvcrt:__clean_type_info_names_internal (0x514114b4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x54ae91a4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50cfc4ac) stub
fixme:msvcrt:__clean_type_info_names_internal (0x55b6a62c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50db335c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50e424cc) stub
fixme:msvcrt:__clean_type_info_names_internal (0x55f2356c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x54b1d33c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5648137c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x54c2479c) stub

**Comment by hillwoodroc** [comment]
用 winetricks 安装 dbghelp 试试。
另外，你的 wine 版本太旧了，建议升级，最新版是没有这个问题的。

329379172 <notifications@github.com>于2016年1月20日周三 11:13写道：

> centos7
> wine-1.7.33
>
> fixme:ras:RasEnumConnectionsW (0xaaeb2c8,0xaaeb26c,0xaaeb270),stub!
> fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure
> program to use LAN connection/winsock instead!
> fixme:crypt:SystemFunction041 (0x2fd7868, 1090, 1): stub [RtlDecryptMemory]
> fixme:crypt:SystemFunction040 (0x2fbf8d0, 1090, 1): stub [RtlEncryptMemory]
> fixme:crypt:SystemFunction041 (0x2fd7868, 1090, 1): stub [RtlDecryptMemory]
> fixme:crypt:SystemFunction040 (0x2fbf8d0, 1090, 1): stub [RtlEncryptMemory]
> fixme:crypt:SystemFunction041 (0x2fd7868, 1090, 1): stub [RtlDecryptMemory]
> fixme:crypt:SystemFunction041 (0x2fd7868, 1090, 1): stub [RtlDecryptMemory]
> fixme:crypt:SystemFunction040 (0x2fbf8d0, 1090, 1): stub [RtlEncryptMemory]
> fixme:file:MoveFileWithProgressW MOVEFILE_WRITE_THROUGH unimplemented
> fixme:ras:RasEnumConnectionsW (0x34cb2c8,0x34cb26c,0x34cb270),stub!
> fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure
> program to use LAN connection/winsock instead!
> fixme:file:MoveFileWithProgressW MOVEFILE_WRITE_THROUGH unimplemented
> fixme:wininet:InternetSetOptionW
> INTERNET_OPTION_SEND/RECEIVE_TIMEOUT/DATA_SEND_TIMEOUT 10
> fixme:heap:HeapSetInformation (nil) 1 (nil) 0
> fixme:dbghelp_dwarf:compute_location Only supporting one reg (edi/24 -> -2)
> fixme:dbghelp_dwarf:compute_location Only supporting one reg (edi/24 -> -2)
> fixme:dbghelp_dwarf:compute_location Only supporting one reg (edi/24 -> -2)
> fixme:dbghelp_dwarf:dwarf2_parse_variable Unsupported constant (parameter)
> pEncodePara in function
> fixme:dbghelp_dwarf:dwarf2_parse_variable Unsupported constant (parameter)
> dwFlags in function
> fixme:resource:GetGuiResources (0xf5c,0): stub
> fixme:dbghelp:elf_search_auxv can't find symbol in module
> fixme:msvcrt:__clean_type_info_names_internal (0x51d57414) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x5584d4f4) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x50dcb38c) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x5633c3a4) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x50d5408c) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x5578c464) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x514114b4) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x54ae91a4) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x50cfc4ac) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x55b6a62c) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x50db335c) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x50e424cc) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x55f2356c) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x54b1d33c) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x5648137c) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x54c2479c) stub
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hillwoodroc/winetricks-zh/issues/32>.
>
-- 

Hillwood Yang
http://hillwoodhome.net
openSUSE member
hillwood@openSUSE.org

**Comment by 329379172** [comment]
@hillwoodroc 
确实,我更新到wine-1.8 之后就一切正常了
非常感谢!
