### ISSUE TITLE
qqlight输入中文成为方块

### ISSUE THREAD

**Issue by changuoqiang** [hillwoodroc/winetricks-zh#34]
显示中文挺正常的，就是输入的时候是方块，消息发送后又显示为正常，怀疑是字体的问题，
env WINEPREFIX=$HOME/.local/share/wineprefixes/qqlight wine regedit导入了如下reg文件:

REGEDIT4

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink]
"Lucida Sans Unicode"="wqy-microhei.ttc"
"Microsoft Sans Serif"="wqy-microhei.ttc"
"MS Sans Serif"="wqy-microhei.ttc"
"Tahoma"="wqy-microhei.ttc"
"Tahoma Bold"="wqy-microhei.ttc"
"SimSun"="wqy-microhei.ttc"
"Arial"="wqy-microhei.ttc"
"Arial Black"="wqy-microhei.ttc"

显示仍然为方块，是QQ的输入框指定了特别的字体吗？

**Comment by changuoqiang** [comment]
输入框改为“文本模式”输入正常，“气泡模式”显示为方块乱码。

**Comment by hillwoodroc** [comment]
wine 的版本是多少？

changuoqiang <notifications@github.com>于2016年1月27日周三 22:10写道：

> 输入框改为“文本模式”输入正常，“气泡模式”显示为方块乱码。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hillwoodroc/winetricks-zh/issues/34#issuecomment-175649626>
> .
>
-- 

Hillwood Yang
http://hillwoodhome.net
openSUSE member
hillwood@openSUSE.org

**Comment by changuoqiang** [comment]
debian stretch系统上的wine 1.8-2, wine --version输出wine-1.8

2016-01-27 22:16 GMT+08:00 Hillwood Yang <notifications@github.com>:

**Comment by Endle** [comment]
请检查一下环境变量
我之前通过设置 LC_ALL=zh_CN.utf8 解决了这个问题

**Comment by changuoqiang** [comment]
好，我用的locale一直是en_US.UTF-8

**Comment by Sengxian** [comment]
这对我很有用，在 Ubuntu 下修改 `/etc/default/locale` 文件即可。

**Comment by alaneuler** [comment]
设置LC_ALL=zh_CN.utf8的确有用，但是把我整个系统的语言全部换成了中文的。。。
有没有什么不改变系统语言的方案？

**Comment by Endle** [comment]
@alaneuler 不用在 `/etc/default/locale`里设置
在终端里，执行 `LC_ALL=zh_CN.utf8 wine xxx.exe`，只在运行时有效

**Comment by alaneuler** [comment]
@Endle 多谢啦，的确有用
