### ISSUE TITLE
建议添加 WINEARCH=win32 参数

### ISSUE THREAD

**Issue by fevenor** [hillwoodroc/winetricks-zh#35]
在64位的Manjaro（基于Archlinux）中，wine默认以64位的方式运行windows程序，添加 WINEARCH=win32 参数才能正常安装及运行。

**Comment by baylin87** [comment]
请问楼上是在哪里添加WINEARCH=win32这个参数？？

**Comment by hillwoodroc** [comment]
请在 $HOME/.bashrc 文件里添加一行 WINEARCH=win32 。
winetricks 部分支持 64 位，所以不会把 WINEARCH=win32 加到 winetricks-zh 里面。
