### ISSUE TITLE
Downloading W2KSP4_EN.EXE failed

### ISSUE THREAD

**Issue by baylin87** [hillwoodroc/winetricks-zh#36]
具体提示：
Downloading http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE failed

**Comment by sqc1999** [comment]
我遇到了相同的问题，似乎是这个下载地址已经失效了

**Comment by sqc1999** [comment]
找到一个解决方法，从其他途径下载W2KSP4_EN.EXE，复制到缓存目录~/.cache/winetricks/win2ksp4/中。

**Comment by baylin87** [comment]
恩恩，目前我也是这样解决的。

**Comment by hentai-mew** [comment]
你们都能这样解决么.... 我如果这样做的话 会自动把目录中的W2KSP4_EN.EXE备份（后缀bak）然后重新下载.... 
wine1.9.6

**Comment by Endle** [comment]
> 你们都能这样解决么.... 我如果这样做的话 会自动把目录中的W2KSP4_EN.EXE备份（后缀bak）然后重新下载....

这是因为文件的 hash 值不匹配

**Comment by hehh2001** [comment]
http://www.filewatcher.com/m/W2KSP4_EN.EXE.135477136-0.html  在这里找最快的站点，替换掉主程序中的相关下载地址就好了。我是这样解决的，

**Comment by Durant35** [comment]
@Hentioe 请问您最后是怎么解决的，我也遇到这个问题了
```sh
$ wine --version
wine-2.1
$ winetricks-zh --version
20160311 - sha1sum: 872bbe1b7ab514f2a84a83f8969c4a5170ba053f
$ 
```

**Comment by Hentioe** [comment]
@Durant35 在这个 issue 上我贴出了下载链接：https://github.com/hillwoodroc/winetricks-zh/issues/41
下载我给出的那个就行了。

**Comment by Durant35** [comment]
恩。看来是翻墙下载短片的缘故（原本100多M，下了个30多M的）
国内的小伙伴可以：http://pan.baidu.com/s/1jIsPbmu
我是通过楼上 http://www.filewatcher.com/m/W2KSP4_EN.EXE.135477136-0.html 这种方式下载，然后直接放到 `~/.cache/winetricks/win2ksp4`

**Comment by sqc1999** [comment]
这个应该能用：http://download.pchome.net/system/patch/detail-15036.html
好久之前下的，记不清是不是从这里下的了。。

**Comment by hillwoodroc** [comment]
配合这个项目可以解决问题： https://github.com/racaljk/hosts
