### ISSUE TITLE
QQ.tar.gz 无法下载

### ISSUE THREAD

**Issue by Heavenser** [hillwoodroc/winetricks-zh#37]
Downloading http://hillwoodhome.net/wine/QQ.tar.gz to /home/heavenser/.cache/winetricks/qq 
QQ.tar.gz 无法下载，浏览器挂VPN也打不开你的博客，请问有其他的途径吗？

**Comment by hillwoodroc** [comment]
我的主机宕机了，正在联系修复。

Heavens Lee <notifications@github.com>于2016年3月2日周三 22:22写道：

> Downloading http://hillwoodhome.net/wine/QQ.tar.gz to
> /home/heavenser/.cache/winetricks/qq
> QQ.tar.gz 无法下载，浏览器挂VPN也打不开你的博客，请问有其他的途径吗？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hillwoodroc/winetricks-zh/issues/37>.
>
-- 

Hillwood Yang
http://hillwoodhome.net
openSUSE member
hillwood@openSUSE.org

**Comment by Heavenser** [comment]
好的，谢谢


发送自 Outlook Mobile






On Wed, Mar 2, 2016 at 6:45 AM -0800, "Hillwood Yang" <notifications@github.com> wrote:





我的主机宕机了，正在联系修复。

Heavens Lee <notifications@github.com>于2016年3月2日周三 22:22写道：

> Downloading http://hillwoodhome.net/wine/QQ.tar.gz to
> /home/heavenser/.cache/winetricks/qq
> QQ.tar.gz 无法下载，浏览器挂VPN也打不开你的博客，请问有其他的途径吗？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hillwoodroc/winetricks-zh/issues/37>.
>
--

Hillwood Yang
http://hillwoodhome.net
openSUSE member
hillwood@openSUSE.org


---

**Comment by hillwoodroc** [comment]
已经恢复。

**Comment by Heavenser** [comment]
多谢告知
2016年3月3日 16:10，Hillwood Yang <notifications@github.com>写道：已经恢复。
