### ISSUE TITLE
安装qqlight时从微软网站下载数据异常

### ISSUE THREAD

**Issue by azure42** [hillwoodroc/winetricks-zh#38]
> 正在连接 download.microsoft.com (download.microsoft.com)|211.90.29.21|:80... 已连接。
> 已发出 HTTP 请求，正在等待回应... 404 Not Found
> 2016-03-19 01:09:20 错误 404：Not Found。

**Comment by DragoonZ** [comment]
微软自家已经撤下久补丁的下载地址了，可以尝试从http://archive.org/web/找存档手动安装

**Comment by azure42** [comment]
http://pan.baidu.com/s/1HTFg6，放到~/.cache/winetricks/win2ksp4/即可

**Comment by hillwoodroc** [comment]
archive.org 已经被墙了，大家还能找到更好的地址吗？各种云盘除外。

**Comment by hillwoodroc** [comment]
请配合这个项目使用 winetricks ： https://github.com/racaljk/hosts
