### ISSUE TITLE
QQ安装完成，一切正常，可是关闭QQ后，怎么打开，

### ISSUE THREAD

**Issue by JSW5297** [hillwoodroc/winetricks-zh#39]
QQ安装完成，一切正常，可是关闭QQ后，或者重启电脑后怎么打开，应用程序里的QQ打不开，安装目录下的QQ也打不开

**Comment by hillwoodroc** [comment]
你用的哪个版本的 wine ?

**Comment by JSW5297** [comment]
官网给的Ubuntu安装方法，是winebuild

**Comment by JSW5297** [comment]
有什么特别版本要求吗？用哪个版本不会有问题呢

**Comment by DragoonZ** [comment]
跟wine版本没关系，脚本自己产生的快捷方式指向的路径不对，自己找～/.local/share/applications/wine/Programs/腾讯软件/QQ轻聊版/QQ轻聊版.desktop

把命令改成env WINEPREFIX=～/.local/share/wineprefixes/qqlight wine "C:\Program Files (x86)\Tencent\QQLite\bin\QQScLauncher.exe"
就好了

生成的好像是env WINEPREFIX=～/.local/share/wineprefixes/qqlight wine "C:\Program Files (x86)\Tencent\QQLite\bin/\QQScLauncher.exe"

**Comment by dachengxi** [comment]
是的，生成的快捷方式好像不对，可能没有修改。我这边修改了有时候也有问题，现在都是打开winetricks-zh-选择容器-启动命令行-然后wine C:\Program Files (x86)\Tencent\QQLite\bin\QQ.exe 运行。

**Comment by hillwoodroc** [comment]
你们都是64位的 wine 吧。删除容器，在运行 winetricks 之前先运行 “export WINEARCH=win32”强制使用32位模式。

**Comment by dachengxi** [comment]
对的，我用的64位的。谢谢提醒~有时间我试试使用32位~~

**Comment by JSW5297** [comment]
每次安装新的软件时都用“export WINEARCH=win32强制改一下？
还是只需要改一次

**Comment by JSW5297** [comment]
我去试试，那岂不是要把现在已安装的都给卸载了重新安装？

**Comment by shiliang-hust** [comment]
可以写bashrc里的 @JSW5297

**Comment by hehh2001** [comment]
有这工具一切看似简单多了，有点问题想问一下大家，QQ装完后表情不能用一闪就过云了，我还要再装什么包吗？？？另外QQGame全是乱码小方格，怎么解决啊？
