### ISSUE TITLE
需要企业 QQ 

### ISSUE THREAD

**Issue by light4** [hillwoodroc/winetricks-zh#4]
可以用 CrossTie 来写 verb 文件么？
下载地址：http://dldir1.qq.com/qqfile/crm/hrtx/HRTX1.89.2036.exe

**Comment by hillwoodroc** [comment]
CrossTie 和 verb 的实现原理相同，但是采用的编写语言不同，所以两者不兼容。但是可以根据内容进行改写。企业 QQ 在我的工作计划里，也许明天就支持，也许是春节后，要看我的空余时间是否足够。

**Comment by hillwoodroc** [comment]
楼主能给个账号作为测试用吗？我没企业QQ账号，无法测试稳定性。

**Comment by light4** [comment]
要不我私信给你，或者你告诉我怎么测试。
Gmail邮箱： lightning1141

**Comment by hillwoodroc** [comment]
hillwoodroc gmail 邮箱。

**Comment by hillwoodroc** [comment]
已加入支持，你可以把密码改回去了，有问题随时回报。
