### ISSUE TITLE
部分软件依赖的资源的下载链接已经失效

### ISSUE THREAD

**Issue by hentai-mew** [hillwoodroc/winetricks-zh#41]
###### 例如安装qqlight.verb时下载的：  
`http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE`  
就已经不存在了，至少在我这边是如此，难不成是我自己的网络问题？不会就我一个吧。。。。

**Comment by hillwoodroc** [comment]
是微软自己删除了。既然很多人都在反应这个问题，那晚上我换一个可用的链接。

**Comment by datahwc** [comment]
我也遇到这个问题，有解决方案吗？

**Comment by SunRain** [comment]
是的，有些资源下不到了，我是直接网络上搜索文件名，手动下载的

**Comment by hentai-mew** [comment]
手动下载:
````
http://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE
````
然后拷贝到"~/.cache/winetricks/win2ksp4"路径下即可。这个issue关闭，大家别回复辣。

**Comment by aofall** [comment]
提醒一下 archive.org 撞墙请注意
