### ISSUE TITLE
wine 的 网易云音乐 全局快捷键不能正常使用。

### ISSUE THREAD

**Issue by zinechant** [hillwoodroc/winetricks-zh#42]
上来发个Issue, 问一下是不是个人问题。
感觉全局快捷键是最重要的功能了。

**Comment by hillwoodroc** [comment]
这是 wine 的问题，只有在将鼠标停留在 wine 程序上才可以激活快捷键。

**Comment by zinechant** [comment]
谢啦.... 最近网易更新api什么的,命令行的`musicbox`海外用户已近基本不能用了....
于是来试试`wine`.
Google 了一下`wine`似乎可以绑定快捷键，我去试试

**Comment by seasonyuu** [comment]
想问下你wine的网易云音乐可以输入中文吗

**Comment by hillwoodroc** [comment]
是可以的。

**Comment by hehh2001** [comment]
已经出LINUX版本了
