### ISSUE TITLE
希望添加对《工作宝》的支持

### ISSUE THREAD

**Issue by heyanlong** [hillwoodroc/winetricks-zh#43]
因工作需要，需要运行工作宝与同事沟通，希望作者添加对工作宝的支持
工作宝地址 http://www.mygzb.com/

**Comment by heyanlong** [comment]
我尝试用默认容器运行，登陆的时候提示 disk full c:\GZB\bin\Log\2016-xx-xx.log

**Comment by hillwoodroc** [comment]
能把哪个 log 文件的内容发来看看吗？

**Comment by heyanlong** [comment]
@hillwoodroc 日志已删，放弃了，弄了个windows虚拟机运行此软件了
