### ISSUE TITLE
QQ轻聊版无法输入中文

### ISSUE THREAD

**Issue by scalpelx** [hillwoodroc/winetricks-zh#44]
输入法：搜狗
Ubuntu 16.04 
Wine 1.9.9
QQ轻聊版7.9

**Comment by hillwoodroc** [comment]
我用 ibus ，无法验证你的问题，建议你在问问其他 fcitx 的用户看能否重现问题，同时请附上你的终端输入日志。

**Comment by scalpelx** [comment]
@hillwoodroc 请问是什么输出日志，是执行fcitx-diagnose输出的信息吗？

**Comment by hillwoodroc** [comment]
就是用终端运行输出的那些信息。

**Comment by scalpelx** [comment]
@hillwoodroc 是这些信息吗？
err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
err:service:process_send_command service protocol error - failed to write pipe!
fixme:service:scmdatabase_autostart_services Auto-start service L"MountMgr" failed to start: 1053
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:advapi:RegisterEventSourceW ((null),L"QPCore"): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000000,(nil),0x0001,0x00000000,0x72e764,(nil)): stub
fixme:advapi:DeregisterEventSource (0xcafe4242) stub
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
scalpel@scalpel:~$ fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow The explorer process failed to start.
fixme:ntdll:NtQueryInformationProcess (process=0xcc) Unimplemented information class: ProcessSessionInformation
fixme:iphlpapi:NotifyAddrChange (Handle 0x179e9e4, overlapped 0x179e9c4): stub
fixme:iphlpapi:CancelIPChangeNotify (overlapped 0x179e9c4): stub
fixme:system:SetProcessDPIAware stub!
fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
fixme:ntdll:NtQueryInformationProcess (process=0x138) Unimplemented information class: ProcessSessionInformation
fixme:sync:GetNamedPipeHandleStateW 0xf8 0x169e9e0 0x169e9e4 (nil) (nil) (nil) 0: semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33e8e8 1 C) semi-stub
fixme:sync:GetNamedPipeHandleStateW 0xf8 0x169e9e0 0x169e9e4 (nil) (nil) (nil) 0: semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f188 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33ef48 1 C) semi-stub
fixme:msctf:TextStoreACPSink_OnLayoutChange STUB:(0x153278)
fixme:msctf:TextStoreACPSink_OnTextChange STUB:(0x153278)
fixme:msctf:TextStoreACPSink_OnLayoutChange STUB:(0x153278)
fixme:msctf:TextStoreACPSink_OnTextChange STUB:(0x153278)
fixme:msctf:TextStoreACPSink_OnSelectionChange STUB:(0x153278)
fixme:msctf:TextStoreACPSink_OnLayoutChange STUB:(0x153278)
fixme:msctf:TextStoreACPSink_OnSelectionChange STUB:(0x153278)
fixme:msctf:TextStoreACPSink_OnSelectionChange STUB:(0x153278)
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33e7b8 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33e588 1 C) semi-stub
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:msctf:TextStoreACPSink_OnLayoutChange STUB:(0x153278)
fixme:sync:GetNamedPipeHandleStateW 0x16c 0xa3be9e0 0xa3be9e4 (nil) (nil) (nil) 0: semi-stub
fixme:system:SetProcessDPIAware stub!
fixme:sync:GetNamedPipeHandleStateW 0xf8 0x169e9e0 0x169e9e4 (nil) (nil) (nil) 0: semi-stub
fixme:msvcrt:type_info_name_internal_method type_info_node parameter ignored
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33fb98 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f968 1 C) semi-stub
fixme:winsock:WS_EnterSingleProtocolW unknown Protocol <0x00000000>
fixme:winsock:WS_EnterSingleProtocolW unknown Protocol <0x00000000>
fixme:winsock:WS_EnterSingleProtocolW unknown Protocol <0x00000000>
fixme:winsock:WS_EnterSingleProtocolW unknown Protocol <0x00000000>
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f178 1 C) semi-stub
fixme:ntdll:NtQueryInformationProcess (process=0x154) Unimplemented information class: ProcessSessionInformation
fixme:sync:GetNamedPipeHandleStateW 0x134 0x19ae9e0 0x19ae9e4 (nil) (nil) (nil) 0: semi-stub
err:ole:create_server class {4f7c9975-eca1-4190-b0eb-e37bc5e40893} not registered
err:ole:CoGetClassObject no class object {4f7c9975-eca1-4190-b0eb-e37bc5e40893} could be created for context 0x4
wine: cannot find L"C:\\Program Files (x86)\\Tencent\\QQLite\\Bin\\TXPlatform.exe"
fixme:sync:GetNamedPipeHandleStateW 0x1a0 0xa5be9e0 0xa5be9e4 (nil) (nil) (nil) 0: semi-stub
err:ole:create_server class {4f7c9975-eca1-4190-b0eb-e37bc5e40893} not registered
err:ole:CoGetClassObject no class object {4f7c9975-eca1-4190-b0eb-e37bc5e40893} could be created for context 0x4
fixme:sync:GetNamedPipeHandleStateW 0x134 0x19ae9e0 0x19ae9e4 (nil) (nil) (nil) 0: semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33e8e8 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f148 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33ef08 1 C) semi-stub
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:winsock:WS_EnterSingleProtocolW unknown Protocol <0x00000000>
fixme:winsock:WS_EnterSingleProtocolW unknown Protocol <0x00000000>
init server success 127.0.0.1 12291
GetDomainXmlFerr:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
romCSCXml, Version=1, SigLen=278, ContentLen=4768
Version1 Verify Start.
Verify OK.
VerifyCSCContent_V1, Verify OK !!!.
fixme:crypt:CryptProtectMemory (0x2e14ce0 112 00000001): stub
fixme:process:GetProcessWorkingSetSize (0xffffffff,0x33efc0,0x33efbc): stub
fixme:crypt:CryptUnprotectMemory (0x2e15038 112 00000001): stub
fixme:crypt:CryptProtectMemory (0x2e16fb8 144 00000001): stub
fixme:crypt:CryptUnprotectMemory (0x2e16ea8 144 00000001): stub
fixme:crypt:CryptProtectMemory (0x2e17510 928 00000001): stub
fixme:msvcrt:__clean_type_info_names_internal (0x547d2c74) stub
fixme:msvcrt:__clean_type_info_names_internal (0x555dc464) stub
fixme:msvcrt:__clean_type_info_names_internal (0x513ee46c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x54a991a4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50cdc4ac) stub
fixme:msvcrt:__clean_type_info_names_internal (0x559ba62c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50d9335c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50e224cc) stub
fixme:msvcrt:__clean_type_info_names_internal (0x55d7356c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x54acd33c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5626137c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x54bd479c) stub
fixme:imm:ImmReleaseContext (0x200f4, 0x1884b8): stub
fixme:crypt:CryptUnprotectMemory (0x2e18568 928 00000001): stub
fixme:crypt:CryptProtectMemory (0x2e17510 928 00000001): stub
fixme:crypt:CryptUnprotectMemory (0x2e18568 928 00000001): stub
fixme:crypt:CryptProtectMemory (0x2e17510 928 00000001): stub
fixme:crypt:CryptUnprotectMemory (0x2e18568 928 00000001): stub
fixme:crypt:CryptProtectMemory (0x2e17510 928 00000001): stub
fixme:crypt:CryptUnprotectMemory (0x2e18568 928 00000001): stub
fixme:crypt:CryptUnprotectMemory (0x2e18568 928 00000001): stub
fixme:crypt:CryptProtectMemory (0x2e17510 928 00000001): stub
fixme:crypt:CryptUnprotectMemory (0x2e18568 928 00000001): stub
fixme:crypt:CryptProtectMemory (0x2e17510 928 00000001): stub
fixme:crypt:CryptUnprotectMemory (0x2e13908 928 00000001): stub
fixme:crypt:CryptProtectMemory (0x2e17510 928 00000001): stub
fixme:crypt:CryptUnprotectMemory (0x2e13908 928 00000001): stub
fixme:crypt:CryptUnprotectMemory (0x2e13908 928 00000001): stub
fixme:crypt:CryptProtectMemory (0x2e17510 928 00000001): stub
err:ole:create_server class {4f7c9975-eca1-4190-b0eb-e37bc5e40893} not registered
err:ole:CoGetClassObject no class object {4f7c9975-eca1-4190-b0eb-e37bc5e40893} could be created for context 0x4
err:ole:create_server class {4f7c9975-eca1-4190-b0eb-e37bc5e40893} not registered
err:ole:CoGetClassObject no class object {4f7c9975-eca1-4190-b0eb-e37bc5e40893} could be created for context 0x4
fixme:msctf:TextStoreACPSink_OnLayoutChange STUB:(0x153278)
fixme:msctf:TextStoreACPSink_OnSelectionChange STUB:(0x153278)
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33ee48 1 C) semi-stub
fixme:sync:GetNamedPipeHandleStateW 0x134 0x19ae9e0 0x19ae9e4 (nil) (nil) (nil) 0: semi-stub
fixme:sync:GetNamedPipeHandleStateW 0x134 0x19ae9e0 0x19ae9e4 (nil) (nil) (nil) 0: semi-stub
fixme:crypt:CryptUnprotectMemory (0x2e13908 928 00000001): stub
fixme:crypt:CryptProtectMemory (0x2e301c8 1280 00000001): stub
fixme:crypt:CryptUnprotectMemory (0x2e2fc40 1280 00000001): stub
fixme:crypt:CryptProtectMemory (0x2e31fa8 3360 00000001): stub
fixme:crypt:CryptUnprotectMemory (0x2e367a8 3360 00000001): stub
fixme:crypt:CryptProtectMemory (0x2e397b0 4112 00000001): stub
err:ole:create_server class {4f7c9975-eca1-4190-b0eb-e37bc5e40893} not registered
err:ole:CoGetClassObject no class object {4f7c9975-eca1-4190-b0eb-e37bc5e40893} could be created for context 0x4
err:ole:create_server class {4f7c9975-eca1-4190-b0eb-e37bc5e40893} not registered
err:ole:CoGetClassObject no class object {4f7c9975-eca1-4190-b0eb-e37bc5e40893} could be created for context 0x4

**Comment by DragoonZ** [comment]
在~/.xinitrc里面添加export XMODIFIERS=@im=fcitx

**Comment by scalpelx** [comment]
@hillwoodroc 还是不行，之前用Ubuntu 15.10时正常，升级到16.04后就不行了

**Comment by DragoonZ** [comment]
注销/重启了么

**Comment by DragoonZ** [comment]
还是发fcitx-diagnose吧

**Comment by scalpelx** [comment]
@DragoonZ 重启了。

# 系统信息:
1.  `uname -a`:

        Linux scalpel 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Ubuntu
        Description:	Ubuntu 16.04 LTS
        Release:	16.04
        Codename:	xenial

3.  `lsb_release -d`:

        Description:	Ubuntu 16.04 LTS

4.  `/etc/lsb-release`:

        DISTRIB_ID=Ubuntu
        DISTRIB_RELEASE=16.04
        DISTRIB_CODENAME=xenial
        DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

5.  `/etc/os-release`:

        NAME="Ubuntu"
        VERSION="16.04 LTS (Xenial Xerus)"
        ID=ubuntu
        ID_LIKE=debian
        PRETTY_NAME="Ubuntu 16.04 LTS"
        VERSION_ID="16.04"
        HOME_URL="http://www.ubuntu.com/"
        SUPPORT_URL="http://help.ubuntu.com/"
        BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
        UBUNTU_CODENAME=xenial

6.  桌面环境:

    桌面环境为 `gnome3`。

7.  Bash 版本：

        BASH_VERSION='4.3.42(1)-release'

# 环境:
1.  DISPLAY:

        DISPLAY=':1'

2.  键盘布局:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+cn+us:2+us:3+inet(evdev)+capslock(escape)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "cn,us,us", ",", "caps:escape"

3.  Locale:

    1.  全部可用 locale:

            C
            C.UTF-8
            en_AG
            en_AG.utf8
            en_AU.utf8
            en_BW.utf8
            en_CA.utf8
            en_DK.utf8
            en_GB.utf8
            en_HK.utf8
            en_IE.utf8
            en_IN
            en_IN.utf8
            en_NG
            en_NG.utf8
            en_NZ.utf8
            en_PH.utf8
            en_SG.utf8
            en_US.utf8
            en_ZA.utf8
            en_ZM
            en_ZM.utf8
            en_ZW.utf8
            POSIX
            zh_CN.utf8
            zh_SG.utf8

    2.  当前 locale:

            LANG=zh_CN.UTF-8
            LANGUAGE=zh_CN:zh
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC="zh_CN.UTF-8"
            LC_TIME="zh_CN.UTF-8"
            LC_COLLATE="zh_CN.UTF-8"
            LC_MONETARY="zh_CN.UTF-8"
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER="zh_CN.UTF-8"
            LC_NAME="zh_CN.UTF-8"
            LC_ADDRESS="zh_CN.UTF-8"
            LC_TELEPHONE="zh_CN.UTF-8"
            LC_MEASUREMENT="zh_CN.UTF-8"
            LC_IDENTIFICATION="zh_CN.UTF-8"
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/scalpel

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/scalpel/.config`)。

    3.  Fcitx 设置目录：

        当前 fcitx 设置目录是 `~/.config/fcitx` (`/home/scalpel/.config/fcitx`)。

5.  当前用户：

    脚本作为 scalpel (1000) 运行。

# Fcitx 状态:
1.  可执行文件:

    在 `/usr/bin/fcitx` 找到了 fcitx.

2.  版本:

    Fcitx 版本: `4.2.9.1`

3.  进程:

    找到了 2 个 fcitx 进程:

         1444 fcitx
         1456 fcitx-dbus-watc

4.  `fcitx-remote`:

    `fcitx-remote` 工作正常.

# Fcitx 配置界面:
1.  配置工具封装：

    在 `/usr/bin/fcitx-configtool` 找到了 fcitx-configtool。

2.  用于 GTK+-2.0 的配置界面：

    **未找到 gtk2 的配置界面.**

3.  用于 GTK+-3.0 的配置界面：

    在 `/usr/bin/fcitx-config-gtk3` 找到了 `fcitx-config-gtk3`。

4.  KDE 的配置界面：

    **`kcmshell4` 未找到.**

# 前端设置:
## Xim:
1.  `${XMODIFIERS}`:

    **环境变量 XMODIFIERS 的值被设为了 "@im=ibus" 而不是 "@im=fcitx". 请检查您是否在某个初始化文件中错误的设置了它的值.**

    **请使用您发行版提供的工具将环境变量 XMODIFIERS 设为 "@im=fcitx" 或者将 `export XMODIFIERS=@im=fcitx` 添加到您的 `~/.xprofile` 中. 参见 [输入法相关的环境变量: XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-cn#XMODIFIERS).**

    从环境变量中获取的 Xim 服务名称为 ibus.

2.  根窗口上的 XIM_SERVERS:

    **Xim 服务名称: "fcitx" 与环境变量中设置的值 "ibus" 不同.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    环境变量 QT4_IM_MODULE 已经正确地设为了 "fcitx".

2.  qt5 - `${QT_IM_MODULE}`:

    **环境变量 QT_IM_MODULE 的值被设为了 "ibus" 而不是 "fcitx". 请检查您是否在某个初始化文件中错误的设置了它的值.**
    **您可能会在 qt5 程序中使用 fcitx 时遇到问题.**

    **请使用您发行版提供的工具将环境变量 QT_IM_MODULE 设为 "fcitx" 或者将 `export QT_IM_MODULE=fcitx` 添加到您的 `~/.xprofile` 中. 参见 [输入法相关的环境变量: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-cn#QT_IM_MODULE).**

3.  Qt 输入法模块文件:
    找到了 Qt5 的输入法模块: `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
    找到了 Qt4 的输入法模块: `/usr/lib/x86_64-linux-gnu/qt4/plugins/inputmethods/qtim-fcitx.so`.

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了 "fcitx".

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **无法找到 gtk 2 的 `gtk-query-immodules`.**

        **无法找到 gtk 2 的 fcitx 输入法模块.**

    2.  gtk 3:

        **无法找到 gtk 3 的 `gtk-query-immodules`.**

        **无法找到 gtk 3 的 fcitx 输入法模块.**

3.  Gtk 输入法模块缓存:

    1.  gtk 2:

        在 `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.30` 的输入法模块缓存.
        版本行:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.30

        已找到 gtk `2.24.30` 的 fcitx 输入法模块.

            "/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        在 `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.18.9` 的输入法模块缓存.
        版本行:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.18.9

        已找到 gtk `3.18.9` 的 fcitx 输入法模块.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

4.  Gtk 输入法模块文件:

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在.

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在.

# 配置:
## Fcitx 插件:
1.  插件配置文件目录:

    找到了 fcitx 插件配置目录: `/usr/share/fcitx/addon`.

2.  插件列表:

    1.  找到了 33 个已启用的插件:

            fcitx-autoeng
            fcitx-autoeng-ng
            fcitx-chttrans
            fcitx-classic-ui
            fcitx-clipboard
            fcitx-cloudpinyin
            fcitx-dbus
            fcitx-freedesktop-notify
            fcitx-fullwidth-char
            fcitx-fullwidth-char-enhance
            fcitx-imselector
            fcitx-ipc
            fcitx-keyboard
            fcitx-kimpanel-ui
            fcitx-lua
            fcitx-notificationitem
            fcitx-pinyin
            fcitx-pinyin-enhance
            fcitx-punc
            fcitx-punc-ng
            fcitx-quickphrase
            fcitx-remote
            fcitx-sogoucloudpinyin
            fcitx-sogoupinyin
            fcitx-spell
            fcitx-sunpinyin
            fcitx-table
            fcitx-unicode
            fcitx-vk
            fcitx-x11
            fcitx-xim
            fcitx-xkb
            fcitx-xkbdbus

    2.  找到了 0 个被禁用的插件:

3.  插件库:

    所有插件所需的库都被找到。

4.  用户界面:

    找到了 2 个已启用的用户界面插件:

        fcitx-classic-ui
        fcitx-kimpanel-ui

    Kimpanel 进程:

         1823 sogou-qimpanel

## 输入法:
1.  找到了 2 个启用的输入法:

        fcitx-keyboard-cn
        sogoupinyin

2.  默认输入法:

    您已经正确的将一个键盘输入法 "fcitx-keyboard-cn" 设为默认.

# 日志:
1.  `date`:

        2016年 05月 19日 星期四 16:46:08 CST

2.  `~/.config/fcitx/log/`:

        总用量 0

3.  `~/.config/fcitx/log/crash.log`:

    `~/.config/fcitx/log/crash.log` 未找到.

**Comment by DragoonZ** [comment]
@scalpelx 

Xim:

${XMODIFIERS}:

环境变量 XMODIFIERS 的值被设为了 "@im=ibus" 而不是 "@im=fcitx". 请检查您是否在某个初始化文件中错误的设置了它的值.

请使用您发行版提供的工具将环境变量 XMODIFIERS 设为 "@im=fcitx" 或者将 export XMODIFIERS=@im=fcitx 添加到您的 ~/.xprofile 中. 参见 输入法相关的环境变量: XMODIFIERS.

从环境变量中获取的 Xim 服务名称为 ibus.

根窗口上的 XIM_SERVERS:

Xim 服务名称: "fcitx" 与环境变量中设置的值 "ibus" 不同.

wine输入法问题一般是因为这个，我之前用ubuntu16.04的时候在xprofile里面写不管用，用的xinitrc，在arch下在xprofile就行

**Comment by scalpelx** [comment]
@DragoonZ 
找到了一个解决方案，是因为ibus-daemon这个文件存在，所以系统才强制设置这两个环境变量为 ibus的，只需要暂时搞掉这个文件，fcitx就正常了，可以输入中文了。
`sudo mv /usr/bin/ibus-daemon /usr/bin/ibus-daemon.bak`
