### ISSUE TITLE
关于QQ的很奇怪的两个现象

### ISSUE THREAD

**Issue by Hentioe** [hillwoodroc/winetricks-zh#47]
1. 我之前在我的笔记本上一直用的Ubuntu，wine也是保持最新版本，用的QQ轻聊版，从安装开始使用的过程中都是没有托盘（在Ubuntu上叫面板）图标的。

然后前不久，我在其他的机器上装了一个全新的Ubuntu，也是最新的wine，安装了QQ轻聊版，奇葩的是QQ托盘图标有后台等功能完全正常，不过也不能记住密码。
于是我把我自己的笔记本上的wine删除，配置删除，连.desktop都删除。重新装了wine和QQ轻聊版，接着更奇葩的是，托盘图标正常了，而且还能记住密码。
（之前我一直以为无法记住密码和后台图标不显示是正常的）

也就是说，其实记住密码和托盘图标都可以没问题的，但是偶尔情况下确实会有问题。不知道各位老司机有没有什么手段能保持这两个功能正常？原因还未知，难道只能不断的删除重装碰运气吗？

**Comment by zhuzhuhuawk** [comment]
你安装Ubuntu的时候，用的是简体中文还是English？

**Comment by ahuixia** [comment]
记住密码这个问题我也是，用着用着就记住密码了==

**Comment by hillwoodroc** [comment]
记不住密码实因为我屏蔽了 txplatform.exe 这个进程，如果不禁用这个进程就会出现关闭了 QQ 后台还会有 QQ 的进程无法退出的 bug 。个人觉得后者比较严重，所以记不住密码就让它记不住呗。
