### ISSUE TITLE
Note: command 'cabextract -q --directory=~/.wine/dosdevices/c:/windows/system32 ～/.wine/dosdevices/c:/windows/temp/_riched20/i386/riched20.dl_' returned status 1. Aborting

### ISSUE THREAD

**Issue by hehh2001** [hillwoodroc/winetricks-zh#48]
安装报错了，

**Comment by hehh2001** [comment]
如何解决啊，环境是：OS: Arch Linux 
                            Kernel: x86_64 Linux 4.5.4-1-ARCH
                            Uptime: 15h 8m
                            Shell: zsh 5.2
                            wine: 1.9.12-1

**Comment by hehh2001** [comment]
好像是riched20.dll的问题，但我检查发现目录下是有这个文件的，我单独安装也是报一样的错误

**Comment by hillwoodroc** [comment]
你系统里面没有安装 cabextract 这个包。

**Comment by hehh2001** [comment]
的确是这个问题，我太粗心了，本来是装了，后来又卸载了，感谢！！！！！

**Comment by hehh2001** [comment]
有这工具一切看似简单多了，还有点问题想问一下当家的，QQ装完后表情不能用一闪就过云了，我还要再装什么包吗？？？另外QQGame全是乱码小方格，怎么解决啊？

**Comment by hillwoodroc** [comment]
你可以参考其他的 .desktop 文件，如果有必要的话我写一个。
