### ISSUE TITLE
可否提供一个类似wine appdb的评分列表

### ISSUE THREAD

**Issue by vobiscum** [hillwoodroc/winetricks-zh#5]
如题，给激励维护者又方便用户。加油！

**Comment by hillwoodroc** [comment]
想法是可以，但是打分系统这种东西我没能力做，如果开源社区有人愿意帮忙弄一个我还是很乐意的。

**Comment by Endle** [comment]
请问，原有的 appdb 主要有哪些缺陷呢？为什么不把信息直接提交到 appdb 上呢？

**Comment by hillwoodroc** [comment]
appdb 只是一个展示相关程序运行状况的地方，是针对用户而不是针对开发者的，所以对 wine 的完善几乎没有帮助。如果你仔细看看 verb 的内容，你可以看到很多 bug ID，那个就是我报到 wine 的 bugzilla 待修复的 bug 编号，目前已经一个 bug 上游已经解决（光影魔术手调用 winhttp 崩溃的bug）。

**Comment by Endle** [comment]
@hillwoodroc commented on [2015年2月20日 GMT+8下午4:30](https://github.com/hillwoodroc/winetricks-zh/issues/5#issuecomment-75204837 "2015-02-20T08:30:53Z - Replied by Github Comment Enhancer"):
> appdb 只是一个展示相关程序运行状况的地方，是针对用户而不是针对开发者的，所以对 wine 的完善几乎没有帮助。如果你仔细看看 verb 的内容，你可以看到很多 bug ID，那个就是我报到 wine 的 bugzilla 待修复的 bug 编号，目前已经一个 bug 上游已经解决（光影魔术手调用 winhttp 崩溃的bug）。

看到了
不过， wine appdb 同样有填写 bug ID 的地方啊，例如我维护的
[CAJViewer](https://appdb.winehq.org/objectManager.php?sClass=version&iId=18637)
有两个 Known Bugs。而在 bug 页面，也可以点击 "AppDB: 	Show Apps affected by this bug"，进入 CAJViewer 在 appdb 的界面

但你提到，
> 对 wine 的完善几乎没有帮助。
我还真不能反对。现有的 appdb 数据库实在是太欠缺维护了

**Comment by hillwoodroc** [comment]
winetricks 虽然只是个简单的 shell 脚本（也不算简单，有接近2W行代码），但是上游对这个脚本的开发流程却非常严格，对于需要纳入上游的容器方案如果需要安装微软的 native dll ，必须向 wine 官方报相应 dll 的调用 bug 并写入 verb 文件才会被允许，这其实同时也在改善 wine 自身的质量。而 AppDB 并没有这个严格要求。

**Comment by Endle** [comment]
@hillwoodroc commented on [2015年2月20日 GMT+8下午9:49](https://github.com/hillwoodroc/winetricks-zh/issues/5#issuecomment-75240223 "2015-02-20T13:49:49Z - Replied by Github Comment Enhancer"):
> winetricks 虽然只是个简单的 shell 脚本（也不算简单，有接近2W行代码），但是上游对这个脚本的开发流程却非常严格，对于需要纳入上游的容器方案如果需要安装微软的 native dll ，必须向 wine 官方报相应 dll 的调用 bug 并写入 verb 文件才会被允许，这其实同时也在改善 wine 自身的质量。而 AppDB 并没有这个严格要求。

恩，AppDB 的审核是个问题 (也是疏于管理)
