### ISSUE TITLE
verb already exists.

### ISSUE THREAD

**Issue by RanchoCooper** [hillwoodroc/winetricks-zh#50]
OS:Arch Linux

Each time install with winetricks-zh 

occured:`" a verb named xxxx already exists "`

even though I `rm .wine .local/share/wineprefixes -rf`

**Comment by lvzongting** [comment]
直接在目录.local/share/wineprefixes  中运行 winetricks qq  即可.

**Comment by coding-happily** [comment]
you can run `winetricks-zh`
chose the box you have bulit and delete it
and then run `winetricks xxx.verb`
