### ISSUE TITLE
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

### ISSUE THREAD

**Issue by willhunger** [hillwoodroc/winetricks-zh#53]
怎么解决？(」ﾟヘﾟ)」
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

**Comment by hillwoodroc** [comment]
你的用户主目录下有一个 .bashrc 的隐藏文件（没有就新建一个），在里面加入一行“ export WINEARCH=win32” ，然后就可以了。
在这之前，记得先清除刚刚创建的配置。
