### ISSUE TITLE
有道云笔记

### ISSUE THREAD

**Issue by lorkoy** [hillwoodroc/winetricks-zh#56]
ubuntu 16.04 安装有道云笔记 sha1sum 不对
------------------------------------------------------
Downloading http://download.ydstatic.com/notewebsite/downloads/YNote.exe to /home/sebastian/.cache/winetricks/youdaonote
--2016-08-19 09:47:56--  http://download.ydstatic.com/notewebsite/downloads/YNote.exe
Resolving download.ydstatic.com (download.ydstatic.com)... 180.97.178.63, 61.136.211.98, 58.220.6.78
Connecting to download.ydstatic.com (download.ydstatic.com)|180.97.178.63|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62737608 (60M) [application/octet-stream]
Saving to: ‘YNote.exe’

YNote.exe                               100%[===============================================================================>]  59.83M   697KB/s    in 2m 12s  

2016-08-19 09:50:09 (463 KB/s) - ‘YNote.exe’ saved [62737608/62737608]

------------------------------------------------------
sha1sum mismatch!  Rename /home/sebastian/.cache/winetricks/youdaonote/YNote.exe and try again.

**Comment by hillwoodroc** [comment]
Fixed.

**Comment by kiwiflydream** [comment]
我下的最新代码，还有这种情况
