### ISSUE TITLE
我的是64位ubuntu，出现了wineserver not found!错误

### ISSUE THREAD

**Issue by Chouzhou** [hillwoodroc/winetricks-zh#57]
该怎么办呀

**Comment by hillwoodroc** [comment]
这个不是 winetricks 的问题。我不是 ubuntu 用户，也不知道原因。

**Comment by Chouzhou** [comment]
这样啊，那你是什么系统呢

**Comment by hillwoodroc** [comment]
openSUSE

**Comment by Chouzhou** [comment]
好的呀，谢啦

Sent from my iPhone

On Aug 19, 2016, at 22:14, Hillwood Yang <notifications@github.com<mailto:notifications@github.com>> wrote:


openSUSE

―

**Comment by hillwoodroc** [comment]
不清楚 ubuntu 的分包方式，在 openSUSE 里面，wineserver 是包含在 wine 的包里面的。

**Comment by Chouzhou** [comment]
嗯哪

Sent from my iPhone

On Aug 19, 2016, at 23:22, Hillwood Yang <notifications@github.com<mailto:notifications@github.com>> wrote:


不清楚 ubuntu 的分包方式，在 openSUSE 里面，wineserver 是包含在 wine 的包里面的。

―
