### ISSUE TITLE
wine1.4版本应用无法运行

### ISSUE THREAD

**Issue by redapple0204** [hillwoodroc/winetricks-zh#58]
我的系统是debian7，最高只能安装wine1.4,请问有什么办法解决这个问题吗

**Comment by redapple0204** [comment]
编译安装的全都是wine64,没法使用啊

**Comment by Endle** [comment]
See <https://wiki.winehq.org/Debian>

**Comment by redapple0204** [comment]
@Endle .这个方法在debian7会缺依赖
