### ISSUE TITLE
QQ轻聊版显示安全组件损坏，无法运行

### ISSUE THREAD

**Issue by zasdza** [hillwoodroc/winetricks-zh#59]
在登陆后一段时间，QQ开始卡顿，主界面显示安全扫描进行中
之后自动下线，无法再开（无法再开这个问题可能是个老问题
退出后重开 提示 “安全组件损坏，请重新下载”

wine可能被当做外挂了……

**Comment by hillwoodroc** [comment]
杀掉 wine 所有进程再开就好了。
