### ISSUE TITLE
企业QQ字体bug

### ISSUE THREAD

**Issue by light4** [hillwoodroc/winetricks-zh#6]
打开对话窗口，上边名字显示为口，下边正常。
![fonts](https://cloud.githubusercontent.com/assets/1318472/6142424/3ae1fc76-b1f1-11e4-9ecf-88687c538100.jpg)

没那么重要，先解决其他 issue 吧。

**Comment by hillwoodroc** [comment]
解决的办法是删除 simsun 或者用 winetricks 把这个容器的 windows 版本改为 windows vista 以上。

**Comment by light4** [comment]
删除 simsun 之后登录界面无法输入帐号。

**Comment by hillwoodroc** [comment]
应该说字体不会影响程序运行，你试试删除容器在重新安装看看。

**Comment by light4** [comment]
删除了 simsun 和容器之后，重新安装，字体依然无法显示。

**Comment by hillwoodroc** [comment]
你说的是那个口口的问题吗？

**Comment by light4** [comment]
是的

**Comment by hillwoodroc** [comment]
这个 bug QQ的任何一个版本都有，解决的办法就是把容器的操作系统版本切换为 winvista 以上。有意思的是如果第一个字符是非中文（包括空格），那么中文就可以正常显示。应该是 wine 处理字体的 bug 。

**Comment by light4** [comment]
嗯，设置成vista以上就行了。
