### ISSUE TITLE
QQ聊天窗口自动弹出

### ISSUE THREAD

**Issue by tomalloc** [hillwoodroc/winetricks-zh#60]
**wine**:wine-1.9.19
**系统**:Debian GNU/Linux 8.6 (jessie)
**发现由此问题的版本**:QQ8.6, QQ轻聊版, TM2013

 情况是我接收到某个人的聊天信息,一旦我打开聊天窗口,然后我把聊天窗口最小化后做其他的事情,
如果我再次受到这个人的聊天信息,聊天窗口会自动弹出.我期望的是QQ提示我就可以了,自动打开会影响工作.

我试过 [https://kf.qq.com/faq/120509Uvu67N130929VNF3IB.html](https://kf.qq.com/faq/120509Uvu67N130929VNF3IB.html)也没用,求指导

**Comment by hillwoodroc** [comment]
GNOME 桌面环境没能重现这个问题，每次都是我去手动激活。

**Comment by tomalloc** [comment]
谢谢.忘记说了,我用的cinnamon桌面.试了下,切换到mate之后没有此问题.

**Comment by HankelBao** [comment]
这个issue有进展吗？ 同使用cinnamon遇到相同问题。
是应该在cinnamon提issue吗？
