### ISSUE TITLE
You are using a 64-bit WINEPREFIX.

### ISSUE THREAD

**Issue by xiaohu7978** [hillwoodroc/winetricks-zh#63]
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX 

运行QQ  总是崩溃。。。。无法使用。

这个怎么解决啊。

**Comment by bubbless** [comment]
你要在 `.zshrc` 或则 `.bashrc`中写入环境变量
```
export WINEPREFIX=$HOME/.config/wine/
export WINEARCH=win32
```
详细请查阅Archlinux的Wiki。
[https://wiki.archlinux.org/index.php/Wine_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#WINEARCH](https://wiki.archlinux.org/index.php/Wine_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#WINEARCH)
