### ISSUE TITLE
请求添加微信上传文件等功能

### ISSUE THREAD

**Issue by jamewhite** [hillwoodroc/winetricks-zh#65]
您好！
使用现在的 WeChat.verb 安装微信，不能实现上传文件、发送表情等功能。
发现将 xpsp3 中的 ole32.dll 替换（原装先于内建）后，可以实现上传文件、发送表情这两个功能（或许 win2ksp4 也可以）。
但是 winetricks 的 dll 中没有 ole32.dll，可不可以在 verb 的后面添加一个 load_ole32()，使之实现上述功能？

**Comment by Durant35** [comment]
你可以详细说明下如何实现的吗？

**Comment by hillwoodroc** [comment]
Fixed.

**Comment by jamewhite** [comment]
THX
