### ISSUE TITLE
微信安装完成后中文乱码，添加LC_ALL变量后正常

### ISSUE THREAD

**Issue by whour** [hillwoodroc/winetricks-zh#66]
使用默认的wechat.verb安装打开中文乱码，系统环境Archlinux+Wine 1.9.21，单独安装字体也不行，后面在启动器加入env环境变量 `LC_ALL=zh_CN.UTF-8` 后正常，
`Exec=env LC_ALL=zh_CN.UTF-8 WINEPREFIX="/home/user/.local/share/wineprefixes/wechat" wine C:\\\\Program\\ Files\\\\Tencent\\\\WeChat\\\\WeChat.exe`
希望把这个环境变量添加到启动器中。

**Comment by Endle** [comment]
你原先系统环境不是UTF-8编码吗？

**Comment by lilydjwg** [comment]
大概是英文？

所谓的乱码，是指显示为方框吗？如果是的话，那是必须设置为中文 locale。就算是真正的 Windows 也一样。

**Comment by oca-john** [comment]
神呀，我的微信终于能用了……-_-||，试了多少次了，终于可以了，感谢！！(我的系统是openSUSE 15.0 ，目前运行正常)

**Comment by yybawang** [comment]
感谢 可以显示中文了，但还是不能输入

**Comment by TomGarden** [comment]
[可以试一下还可以](https://askubuntu.com/a/1133157/872912):https://askubuntu.com/a/1133157/872912

**Comment by thunder951413** [comment]
我发现deep wine的应用都是被 /opt/deepinwine/tools/run.sh 这个脚本带起来的，
我在这个脚本的开头加了一句export LC_ALL=zh_CN.UTF-8，现在乱码问题都解决了
