### ISSUE TITLE
网易云音乐播放异常报告

### ISSUE THREAD

**Issue by maxadjsky** [hillwoodroc/winetricks-zh#7]
我的系统是openSuse13.1。wine-1.7.36。网易云音乐播放（包括本地和网络的）一顿一顿的，基本上音乐的所谓美感都破坏了。播放网络音乐的时候，有时候播放速度很快，一秒钟能放3-4秒的音乐。

**Comment by hillwoodroc** [comment]
在办公室的 openSUSE 13.1 上测试了下，无法重现你的问题。你的问题是总是出现还是偶尔出现？

**Comment by maxadjsky** [comment]
播放速度快的问题是偶发现象，但是播放音乐一顿一顿的是总是出现的，不管是本地音乐还是网络音乐

**Comment by hillwoodroc** [comment]
能把终端输出日志贴上来吗？
直接运行命令 
env WINEPREFIX="/home/hillwood/.local/share/wineprefixes/163music" wine C:\\windows\\command\\start.exe /Unix /home/hillwood/.local/share/wineprefixes/163music/dosdevices/c:/users/Public/桌面/网易云音乐.lnk

**Comment by LastAvenger** [comment]
Hello hillwood:
  我的openSUSE 13.2 x86_64  wine-1.7.28 上也出现了播放卡顿的问题；
> env WINEPREFIX="/home/la/.local/share/wineprefixes/163music" wine C:\\windows\\command\\start.exe /Unix /home/la/.local/share/wineprefixes/163music/dosdevices/c:/users/Public/桌面/网易云音乐.lnk 2>~/163.log 

日志： 
> fixme:exec:SHELL_execute flags ignored: 0x00000100
fixme:exec:SHELL_execute flags ignored: 0x00004100
fixme:heap:HeapSetInformation (nil) 1 (nil) 0
fixme:process:SetProcessDEPPolicy (3): stub
fixme:heap:HeapSetInformation (nil) 1 (nil) 0
fixme:ntdll:NtIsProcessInJob stub: 0xffffffff (nil)
fixme:imm:ImmDisableTextFrameService Stub
fixme:thread:GetThreadPreferredUILanguages 56, 0x33f0f0, (nil) 0x33f0f4
fixme:winsock:WSALookupServiceBeginW (0x33efc0 0x00000ff0 0x33effc) Stub!
fixme:iphlpapi:NotifyAddrChange (Handle 0x33f12c, overlapped 0x3fc7d68): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x10052, filter=0x33f138,flags=0x00000000) returns a fake device notification handle!
fixme:win:RegisterDeviceNotificationW (hwnd=0x10052, filter=0x33f138,flags=0x00000000) returns a fake device notification handle!
fixme:win:EnumDisplayDevicesW ((null),0,0x33ea7c,0x00000000), stub!
fixme:ver:GetCurrentPackageId (0x609e258 (nil)): stub
fixme:wincodecs:PngDecoder_Block_GetCount stub
fixme:wtsapi:WTSRegisterSessionNotification Stub 0x10074 0x00000000
fixme:msctf:InputProcessorProfileMgr_GetActiveProfile (0x150bc0)->({34745c63-b2f0-4784-8b67-5e12c8701a31} 0x33eb7c)
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
fixme:advapi:RegisterTraceGuidsW (0x12228d0, 0x34a6468, {3dada31d-19ef-4dc1-b345-037927193422}, 1, 0x346e32c, (null), (null), 0x34a6480): stub
fixme:heap:HeapSetInformation (nil) 1 (nil) 0
fixme:process:SetProcessDEPPolicy (3): stub
fixme:heap:HeapSetInformation (nil) 1 (nil) 0
fixme:ntdll:NtIsProcessInJob stub: 0xffffffff (nil)
fixme:advapi:RegisterTraceGuidsW (0x12228d0, 0x34a6468, {3dada31d-19ef-4dc1-b345-037927193422}, 1, 0x346e32c, (null), (null), 0x34a6480): stub
fixme:gdi:GdiInitializeLanguagePack stub
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:ver:GetCurrentPackageId (0x559e9f8 (nil)): stub
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 74080 (device=7 access=1 func=20 method=0)
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d0c10 (device=2d access=0 func=304 method=0)
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 74080 (device=7 access=1 func=20 method=0)
err:ole:CoInitializeEx Attempt to change threading model of this apartment from apartment threaded to multi-threaded
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:gdiplus:GdipGetFamilyName No support for handling of multiple languages!
fixme:winsock:WSALookupServiceBeginW (0x67ae490 0x00000ff0 0x67ae4d8) Stub!
fixme:iphlpapi:NotifyAddrChange (Handle 0x67ae368, overlapped 0x463bd70): stub
fixme:winsock:WSALookupServiceBeginW (0x67ae4c8 0x00000ff0 0x67ae510) Stub!
fixme:winsock:WSALookupServiceBeginW (0x67ae42c 0x00000ff0 0x67ae474) Stub!
fixme:winsock:WSALookupServiceBeginW (0x67ae430 0x00000ff0 0x67ae478) Stub!
fixme:winsock:WSALookupServiceBeginW (0x67ae424 0x00000ff0 0x67ae46c) Stub!
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:file:K32GetMappedFileNameW (0xffffffff, 0x9210000, 0x33e830, 270): stub
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:file:K32GetMappedFileNameW (0xffffffff, 0x9fd0000, 0x33e830, 270): stub
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:system:SystemParametersInfoW Unknown action: 116
fixme:ntdll:NtIsProcessInJob stub: 0x2a4 (nil)
fixme:wtsapi:WTSUnRegisterSessionNotification Stub 0x10074
fixme:iphlpapi:CancelIPChangeNotify (overlapped 0x463bd70): stub
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:iphlpapi:CancelIPChangeNotify (overlapped 0x3fc7d68): stub
fixme:advapi:UnregisterTraceGuids 0: stub

**Comment by taotie12010** [comment]
同网易云音乐卡顿,但没发现倍速的情况

**Comment by 1dot75cm** [comment]
同卡顿, fedora 22

**Comment by hillwoodroc** [comment]
笔记本上完全正常，台式机上确实有问题。目前无解，只能等上游修复。

**Comment by Endle** [comment]
[**@hillwoodroc**](https://github.com/hillwoodroc) commented on [11 Jul 2015, 23:36 GMT+8](https://github.com/hillwoodroc/winetricks-zh/issues/7#issuecomment-120634426 "2015-07-11T15:36:10Z - Replied by Github Comment Enhancer"):
> 笔记本上完全正常，台式机上确实有问题。目前无解，只能等上游修复。

请问有上游的 bug 链接吗？

另外，在能否找到没有该异常的旧版本的 wine ？

**Comment by hillwoodroc** [comment]
https://bugs.winehq.org/show_bug.cgi?id=38028
这其实是 directx 的支持还不完善。

**Comment by zasdza** [comment]
我在Mint上面试了下：
在HDD上装会卡，换到SSD就没问题。
看起来是IO的问题。

**Comment by hillwoodroc** [comment]
确认是 IO 的问题，的确换 SSD 就解决问题。

**Comment by zasdza** [comment]
但windows下显然HDD正常，所以原因依旧不明……

**Comment by MFamilys** [comment]
ubuntu14.04路过，关于卡顿问题，在无SSD的情况下,可使用tmpfs将目录挂载到内存上，问题解决。类似命令：sudo mount tmpfs /home/mfamilys/.wine/drive_c/users/mfamilys/Local\ Settings/Application\ Data/Netease/CloudMusic -t tmpfs -o size=1024m.

**Comment by Sunappnio** [comment]
谢谢作者，网易云音乐播放很好，但是没法最小化到托盘，程序里也没法右键
crossover是可以的，不知道wine怎么配置啊

**Comment by hillwoodroc** [comment]
无法重现楼上的问题，GNOME 桌面正常。

**Comment by Sunappnio** [comment]
@hillwoodroc 好吧，可能我的环境自己有问题，用的是[chroot](https://github.com/dnschneid/crouton)的方法所以是3.14的内核

**Comment by 329379172** [comment]
@MFamilys 挺好用的，不会卡了  学习了

**Comment by lenkey** [comment]
@MFamilys 这个方法挺好，注意路径修改成自己的

**Comment by AlbertYang** [comment]
@lenkey 可是我执行挂载命令后目录被清空了啊～

**Comment by shiliang-hust** [comment]
挂载就是这样，这不是问题@AlbertYang

**Comment by JSW5297** [comment]
为什么我是SSD播放的时候还是会卡顿，昨天不卡，今天运行 “export WINEARCH=win32” 之后重新安装的，之后就会卡了

**Comment by hillwoodroc** [comment]
Linux 原生版已发布，关闭该 issues.
