### ISSUE TITLE
又是32位和64位的问题了，真的不知道如何解决

### ISSUE THREAD

**Issue by willhunger** [hillwoodroc/winetricks-zh#70]
`will@will-pc:~$ winetricks qqlight
------------------------------------------------------
wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "wine: WINEARCH set to win32 but '/home/will/.wine' is a 64-bit installation." 
`

我已经在.bashc下加了
export WINEPREFIX=$HOME/.config/wine/
export WINEARCH=win32

**Comment by shiliang-hust** [comment]
假如wineprefix指定的目录存在的话，wine就会认为它是一个64-bit installation，不管它是不是空的。你可以把$HOME/.config/wine/删掉试试。
