### ISSUE TITLE
微信的显示问题

### ISSUE THREAD

**Issue by AlinJiang** [hillwoodroc/winetricks-zh#72]
打开后屏幕中间总是有一个透明的框，这个框的显示总是比屏幕的内容要慢，导致中间这个框看起来总是像拖影，然后会慢慢的刷新。

**Comment by tomalloc** [comment]
这个把窗口缩小后，再重新打开就没了

**Comment by hillwoodroc** [comment]
这是 wine 对 windows 的阴影特效支持不完善造成的，建议到 wine 的官方报一个 bug .
