### ISSUE TITLE
qq的表情框问题

### ISSUE THREAD

**Issue by AlinJiang** [hillwoodroc/winetricks-zh#73]
qq的表情框，不论是鼠标移动到图标上弹出的小框还是点击进入弹出的大框，内容都无法消失，并且在相应的区域产生拖影，就像隔壁一个issue里面微信叙述的问题一样，一个透明的框。

**Comment by hillwoodroc** [comment]
这个是 wine 处理窗口特效的问题，请将问题反馈到 wine 的 bugzilla 上去。
