### ISSUE TITLE
关于wintricks使用时遇到的问题

### ISSUE THREAD

**Issue by Qing1997** [hillwoodroc/winetricks-zh#76]
很抱歉打扰了，我在使用的时候总是有如下bug提示：bug: a verb named qq already exists.
请问这是什么原因？我尝试了很多方法，将wine卸载安装，删除.wine,进入local/share/win../删除qq。verb都不行，请问该如何解决？

**Comment by hillwoodroc** [comment]
因为 winetricks 已经支持了 QQ ，如果还使用 verb 文件来安装就会提示冲突。直接用 winetricks安装就行了，不需要 verb
文件。

2016年12月22日 17:45，"Qing1997" <notifications@github.com>写道：

**Comment by abcfy2** [comment]
但是qq轻聊版在winetrics没有啊，安装verb/qqlight.verb的时候一样有这个错误

**Comment by hillwoodroc** [comment]
这不是个问题。如果安装 QQ ，请不要直接使用 verb 文件，要么直接运行 winetricks，要么直接运行 winetricks-zh.
