### ISSUE TITLE
安装微信时出现的问题

### ISSUE THREAD

**Issue by lielie976** [hillwoodroc/winetricks-zh#77]
使用"winetricks-zh wechat"命令安装微信时，发现下载了两遍WeChatSetup.exe，
第一次下载速度很快，第二次速度奇慢，而且经常断开连接，能不能加一个功能，
当我手动下载并且放到对应的目录后，程序可以检测到并略过下载。

**Comment by hillwoodroc** [comment]
我更新一下 sha1sum ，应该是版本更新了。最近很忙，一直没时间更新。

**Comment by hillwoodroc** [comment]
Fixed.
