### ISSUE TITLE
qq轻聊版 点查找则卡死

### ISSUE THREAD

**Issue by wooowooo** [hillwoodroc/winetricks-zh#78]
winetricks-zh 用的是 git20160104

wine 1.8.6
安装时用我了winearch=win32

系统中装有winetricks , 所以安装qq的命令是winetricks qqlight.verb

点面版下面的查找按钮,查找窗口弹出后qq卡死

![screenshot_20170121_192952](https://cloud.githubusercontent.com/assets/12052610/22174070/043d0d2e-e010-11e6-8be8-86d52054e820.png)

**Comment by hillwoodroc** [comment]
wine 的 bug, 很早就报过。目前替代的办法是不要打开独立的查找窗口，用主面板自带的查找功能。

**Comment by wooowooo** [comment]
好吧.

不过也补充一下终端输出
`fixme:crypt:CryptProtectMemory (0x2e1fde0 4240 00000001): stub
fixme:arp:wmain stub: L"arp" L"-a"
fixme:process:SetProcessDEPPolicy (1): stub
fixme:system:SetProcessDPIAware stub!
fixme:imm:ImmDisableTextFrameService Stub
fixme:nls:GetThreadPreferredUILanguages 00000038, 0xb0ce64c, (nil) 0xb0ce650
fixme:nls:get_dummy_preferred_ui_language (0x38 0xb0ce64c (nil) 0xb0ce650) returning a dummy value (current locale)
fixme:nls:GetThreadPreferredUILanguages 00000038, 0xb0ce64c, 0x981af60 0xb0ce650
fixme:nls:get_dummy_preferred_ui_language (0x38 0xb0ce64c 0x981af60 0xb0ce650) returning a dummy value (current locale)
fixme:winsock:WSALookupServiceBeginW (0xb0ce558 0x00000ff0 0xb0ce594) Stub!
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0xb0ce2bc 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0xb0ce0bc 1 C) semi-stub
[0201/104107:ERROR:network_change_notifier_win.cc(160)] WSALookupServiceBegin failed with: 8
fixme:iphlpapi:NotifyAddrChange (Handle 0xb0ce6e0, overlapped 0x6853e88): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x2007c, filter=0xb0ce6b8,flags=0x00000000) returns a fake device notification handle!
fixme:win:RegisterDeviceNotificationW (hwnd=0x2007c, filter=0xb0ce6b8,flags=0x00000000) returns a fake device notification handle!
[0201/104107:ERROR:gpu_info_collector_win.cc(102)] Can't retrieve a valid WinSAT assessment.
fixme:win:EnumDisplayDevicesW ((null),0,0xb0cdd6c,0x00000000), stub!
fixme:ntdll:EtwRegisterTraceGuidsW (0x531a549d, 0x547d2da8, {3dada31d-19ef-4dc1-b345-037927193422}, 1, 0x547d2de0, (null), (null), 0x547d2dc0): stub
fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {00000000-0000-0000-0000-000000000000}
fixme:ntdll:NtQueryInformationJobObject stub: (nil) 2 0xbace45c 48 (nil)
fixme:winsock:WSALookupServiceBeginW (0xb0cce94 0x00000ff0 0xb0cced0) Stub!
[0201/104107:ERROR:network_change_notifier_win.cc(160)] WSALookupServiceBegin failed with: 8
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:process:SetProcessDEPPolicy (1): stub
fixme:system:SetProcessDPIAware stub!
fixme:ntdll:EtwRegisterTraceGuidsW (0x531a549d, 0x547d2da8, {3dada31d-19ef-4dc1-b345-037927193422}, 1, 0x547d2de0, (null), (null), 0x547d2dc0): stub
fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {00000000-0000-0000-0000-000000000000}
fixme:msvcrt:MSVCRT__set_abort_behavior _WRITE_CALL_REPORTFAULT unhandled
fixme:gdi:GdiInitializeLanguagePack stub
fixme:crypt:CryptUnprotectMemory (0x2e357d0 4240 00000001): stub
fixme:crypt:CryptProtectMemory (0x2e1fde0 4240 00000001): stub
fixme:ras:RasEnumConnectionsW (0xcdfb1f8,0xcdfb19c,0xcdfb1a0),stub!
fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
fixme:winsock:WSALookupServiceBeginW (0xbcce35c 0x00000ff0 0xbcce398) Stub!
[0201/104107:ERROR:network_change_notifier_win.cc(160)] WSALookupServiceBegin failed with: 8
fixme:heap:RtlCompactHeap (0x420000, 0x0) stub
fixme:arp:wmain stub: L"arp" L"-a"
fixme:ras:RasEnumConnectionsW (0xd40b1f8,0xd40b19c,0xd40b1a0),stub!
fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
fixme:ras:RasEnumConnectionsW (0xd40b1f8,0xd40b19c,0xd40b1a0),stub!
fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
fixme:winsock:WSALookupServiceBeginW (0xbcce35c 0x00000ff0 0xbcce398) Stub!
[0201/104115:ERROR:network_change_notifier_win.cc(160)] WSALookupServiceBegin failed with: 8
fixme:ras:RasEnumConnectionsW (0xd40b1f8,0xd40b19c,0xd40b1a0),stub!
fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
fixme:ras:RasEnumConnectionsW (0xd40b1f8,0xd40b19c,0xd40b1a0),stub!
fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
fixme:ras:RasEnumConnectionsW (0xd40b1f8,0xd40b19c,0xd40b1a0),stub!
fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
`
