### ISSUE TITLE
qq轻聊版 离线后登不上

### ISSUE THREAD

**Issue by wooowooo** [hillwoodroc/winetricks-zh#79]
一旦离线,再试图登录则提示 登录超时 错误码0x00070001

winetricks-zh 用的是 git20160104
wine 1.8.6
winearch=win32

**Comment by IsoaSFlus** [comment]
这些问题不应该是wine的锅吗？我感觉短期内可能无法解决吧。

**Comment by hillwoodroc** [comment]
退出 QQ 重新打开就可以登陆。
