### ISSUE TITLE
QQ轻聊版安装提示路径无效（Debian 8）

### ISSUE THREAD

**Issue by tonghuix** [hillwoodroc/winetricks-zh#8]
安装QQ轻聊版，在安装界面提示我

安装路径无效，您没有权限在此位置写入数据。请重新选择。

系统是Debian 8，wine的版本是1.6.2

**Comment by hillwoodroc** [comment]
这是 wine 的 bug ，1.7.25 版本（好像是这个版本）修复了这个 bug。最新的开发版没有问题。

**Comment by tonghuix** [comment]
问题得解。帮助一下别人，我把过程记录在此。
安装软件包 wine-development。然后在命令行下执行  
     WINE=wine-development winetricks verb/qqlight.verb
就可以了正常安装了
