### ISSUE TITLE
对某些 verb 没有必要生成单独的 prefix

### ISSUE THREAD

**Issue by brglng** [hillwoodroc/winetricks-zh#82]
目前的情况下，执行 list-all，prefix=foo 这样的命令时也会生成名字叫 list-all、prefix=foo 这样的 prefix 目录，是没有必要的。

**Comment by hillwoodroc** [comment]
原版 winetricks 有这个问题吗？

**Comment by hillwoodroc** [comment]
我试了下，最新版没有这个问题了。

**Comment by brglng** [comment]
确实没有问题了。谢谢。

**Comment by brglng** [comment]
这个问题似乎又重新出现了
