### ISSUE TITLE
Wechat 表情&上传文件&截图 无法正常使用

### ISSUE THREAD

**Issue by Durant35** [hillwoodroc/winetricks-zh#83]
+ OS：Ubuntu16.04 
+ 下面是使用的wine和winetricks（应该是最新的）版本信息
```sh
$ wine --version
wine-2.1
$ winetricks-zh --version
20160311 - sha1sum: 872bbe1b7ab514f2a84a83f8969c4a5170ba053f
$ 
```
+ Solutions maybe here：https://github.com/hillwoodroc/winetricks-zh/issues/65

**Comment by jamewhite** [comment]
可以从 xpsp3 文件中找到 ole32.dl_（win2ksp4或许也可以），这是一个cab文件，再从中提取出 ole32.dll，将其拷贝到 system32 目录内或 WeChat 程序文件夹中，最后在 winecfg 中添加 ole32 替换（原装先于内建），表情、上传文件都可以使用了，截图没试过。
个人采取的是手动方法，当然也可以采用自动方法，就是在脚本中类似 load_riched20 加入 load_ole32，实现上述功能。

**Comment by jamewhite** [comment]
刚试了一下，截图也是可以的。

**Comment by Durant35** [comment]
Great! 能否分享下您的`ole32.dll`？按照您的方法（之前也试过），没找到，可能我弄错了

**Comment by jamewhite** [comment]
[ole32.dll.zip](https://github.com/hillwoodroc/winetricks-zh/files/789158/ole32.dll.zip)
xpsp3微软官网上已经404了，要通过 Web Archive 下载，需要挂梯子：
https://web.archive.org/web/http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe

**Comment by hillwoodroc** [comment]
Please review pull request https://github.com/Winetricks/winetricks/pull/754, I will fix this issue after upstream accept my pull request.

**Comment by hillwoodroc** [comment]
Fixed. https://github.com/hillwoodroc/winetricks-zh/commit/15e5d1c41e36869196df7c0ae8e5e18c49c6f83c
