### ISSUE TITLE
希望添加腾讯TIM

### ISSUE THREAD

**Issue by abcfy2** [hillwoodroc/winetricks-zh#85]
QQ轻聊版似乎已经不再维护了，腾讯推出了TIM替代QQ轻聊版。希望可以wine成功: https://office.qq.com/

**Comment by abcfy2** [comment]
自己试着弄了下，似乎只需要装个riched20就行了。还缺个desktop文件的生成

**Comment by hillwoodroc** [comment]
wine 2.0 以上已经不需要 riched20 。抱歉，这几天摔伤住院，一直没弄上去。

2017年3月14日 09:48，"Feng Yu" <notifications@github.com>写道：

**Comment by abcfy2** [comment]
我现在是linuxmint 18.1系统，用的是wine-devel包，已经是2.3版本了。但是我发现不装riched20的话，账号输入不了，只能输入密码。对wine了解不是很透彻，终端上滚屏的一大堆，不明白问题所在。按照古老的资料，安装riched20之后，就一切正常了。

还有个问题没解决，就是最小化聊天窗的时候，只要有聊天信息，就会自动弹出来，很讨厌，不知道怎么解决。记得以前1.7还是1.8开始，某个版本开始就引入这个问题了，直到现在依旧没解决。

**Comment by IsoaSFlus** [comment]
同希望添加tim，祝作者大大早日康复。

**Comment by wooowooo** [comment]
赞同添加！

祝作者早日康复！

**Comment by willhunger** [comment]
希望添加,祝大大快点好起来

**Comment by hillwoodroc** [comment]
已搞定。

**Comment by abcfy2** [comment]
遇到两个问题，不知道大大有解决方案没。

1. 点击链接会弹出wine internet explorer，以前我记得是调用系统浏览器。不知道这个怎么调。
2. 最小化窗口后，如果有聊天提醒会自动弹出，这个很讨厌。不知道有没有方案？

祝好！

**Comment by IsoaSFlus** [comment]
@abcfy2 第一个问题我也遇到了，第二我倒是没有，但我记得tim的设置里面好像有设置是否自动弹出的地方。

**Comment by abcfy2** [comment]
@IsoaSFlus 第二个问题其实不是TIM的问题，我感觉是wine的问题。从wine 1.7.x某个版本引入的，至今未修复。以前wine qq的时候，在Linuxmint下跑就会遇到这个问题。

**Comment by hillwoodroc** [comment]
在 winecfg 里面把 windows 版本设成 XP 就行了。

2017年3月22日 13:41，"Will" <notifications@github.com>写道：
