### ISSUE TITLE
希望默认浏览器调用原生浏览器不用ie

### ISSUE THREAD

**Issue by yswtrue** [hillwoodroc/winetricks-zh#88]
rt，wine的ie有点坑，以前是可以调用原生浏览器的我记得，后来重装系统就变成ie了。
是不是上游wine改变了呢

**Comment by SunRain** [comment]
同上,不知道哪里可以设置

**Comment by hillwoodroc** [comment]
在 winecfg 里面把 windows 版本更改为 Windows XP 或者 Windows 2003.

**Comment by yswtrue** [comment]
那可以让他默认是xp版本的吗，手工调整有点麻烦

**Comment by hillwoodroc** [comment]
我先报个 bug 再修复。

**Comment by hillwoodroc** [comment]
Fixed in https://github.com/hillwoodroc/winetricks-zh/commit/cf1afa785c5d308a07e1c67b51ac231233e0764d

**Comment by hillwoodroc** [comment]
经核实这个问题还不是 wine 的锅，是鹅厂的问题：
