### ISSUE TITLE
我在安装QQGAME的时候IE8是无法下载的！

### ISSUE THREAD

**Issue by behind1231** [hillwoodroc/winetricks-zh#9]
作者，如上题，能把一些下载的IE8等软件共享一下吗？有些不知道是什么原因是下载超时，我网络是光纤来的！

**Comment by light4** [comment]
可以先用下载软件下载下来，终端里就有下载地址，然后放到缓存文件夹里边。

**Comment by hillwoodroc** [comment]
这个就得问方校长为什么要封 googlecode 了，有些文件是从这上面下载的。翻墙就能解决。

**Comment by hillwoodroc** [comment]
新版本已修复。
