### ISSUE TITLE
TIM1.0.5 的 hash 值是不是不对

### ISSUE THREAD

**Issue by Hentioe** [hillwoodroc/winetricks-zh#90]
拉取了你最新的 commit，然后安装 tim.verb，会出现：

sha1sum mismatch!  Rename /home/hentioe/.cache/winetricks/tim/TIM1.0.5.exe and try again.

注意，这在 1.0.4 版本的时候是没问题的。莫非腾讯在同一个链接下替换了原来的资源文件？

**Comment by hillwoodroc** [comment]
Fixed in https://github.com/hillwoodroc/winetricks-zh/commit/dd69fa20aadccdcf5d4dfa05ae58ff054c889238
