### ISSUE TITLE
64位wine安装问题

### ISSUE THREAD

**Issue by versee** [hillwoodroc/winetricks-zh#92]
作者你好，我想安装TIM的时候报错如下：
------------------------------------------------------
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20170327-next - sha256sum: 4ac14f30656f2ee96543117640c0f14382de41c4bc79d64fd80c0ab5fada0107 with wine-1.6.2 and WINEARCH=win64
20170327
/usr/bin/winetricks-zh: 19759: .: Can't open ./tim.verb

我系统是64位mint，想知道怎么解决

**Comment by hillwoodroc** [comment]
verb 文件是给原版 winetricks 用的，winetricks-zh 已经内置了 tim ，不需要 verb 文件。另外，你的 wine 8是在太老了，必须升级。
