### ISSUE TITLE
wechat checksum mismatch

### ISSUE THREAD

**Issue by hejianhui** [hillwoodroc/winetricks-zh#94]
今天尝试安装微信，提示
sha256sum mismatch!  Rename /home/user/.cache/winetricks/wechat/WeChatSetup.exe and try again.

如果需要提供log的话，请告诉我log在哪里，我第一次用winetricks

**Comment by hillwoodroc** [comment]
是鹅厂升级了，我更新一下。

2017年4月28日 16:17，"何剑辉" <notifications@github.com>写道：

**Comment by hejianhui** [comment]
另外我还想请教下，为什么我下载InstMsiW.exe和W2KSP4_EN.EXE也会提示checksum mismatch，但是从http://www.filewatcher.coml这里下载的文件就不会？checksum mismatch是bug吗？什么原因造成的？

**Comment by hejianhui** [comment]
谢谢，我还没试，之前已经从别的地方下载了wechat了

**Comment by hillwoodroc** [comment]
Fixed.
