### ISSUE TITLE
W2KSP4_EN.EXE地址失效

### ISSUE THREAD

**Issue by imxieyi** [hillwoodroc/winetricks-zh#95]
http://x3270.bgp.nu/download/specials/W2KSP4_EN.EXE
这个地址目前可用

**Comment by imxieyi** [comment]
还有InstMsiW.exe
http://www.filewatcher.com/m/instmsiw.exe.1822520-1.html
建议加入自动到上面这个网站查找下载地址的功能

**Comment by holmeszyx** [comment]
打包了份用到的patch，
https://pan.baidu.com/s/1mhY6jw8

#### 包括
- msls31
- vcrun6
- wenquanyi
- win2ksp4
- winxpsp3

解压，丢`~/.cache/winetricks/`里面，应试可以直接用了。
我在另一机子上是这么装的

**Comment by hillwoodroc** [comment]
Fixed by upstream.
