### ISSUE TITLE
图标文件编码问题

### ISSUE THREAD

**Issue by xcffl** [hillwoodroc/winetricks-zh#96]
似乎通过 winetricks-zh 安装的程序的桌面图标文件（xxx.desktop）采用的是 ASCII 编码，但 Ubuntu 需要的是 UTF-8 编码。使用 ASCII 编码会导致 Gnome 无法索引这个程序。

**Comment by hillwoodroc** [comment]
启动器并不是 winetricks 创建的（除了 QQ ），而是 wine 创建的。如果你认为这是 bug ，请到 wine 的 bugzilla 报告。
