### ISSUE TITLE
安装qq失败

### ISSUE THREAD

**Issue by qianguyingkui** [hillwoodroc/winetricks-zh#99]
Checksum for /home/***/.cache/winetricks/qq/QQ8.9.1.exe did not match, retrying download
请问是什么原因造成的呢？

**Comment by qianguyingkui** [comment]
修改sha1sum后已解决……谢谢

**Comment by SMZCC** [comment]
请问下sha1sum是什么？按照什么原则进行修改？如何修改？
谢谢 @yklove

**Comment by yklove** [comment]
@SMZCC 查看 qq.verb 文件  第14、15行，按照下载链接下载文件，计算sha1sum ，将计算结果替换原来的sha1sum
